### ISSUE TITLE
The UI doesn't load on macOS safari

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#1027]
Just seeing this error in the console: `SyntaxError: Invalid regular expression: invalid group specifier name`.

<img width="1840" alt="Screenshot 2023-09-01 at 13 09 52" src="https://github.com/radicle-dev/radicle-interface/assets/158411/4632de54-a921-4a48-89de-bcc8e2e6033e">
<img width="396" alt="Screenshot 2023-09-01 at 13 10 06" src="https://github.com/radicle-dev/radicle-interface/assets/158411/dcc9fd47-cc0d-4db1-83ef-31f55a670feb">

**Comment by sebastinez** [comment]
Ok it seems like this issue has to do with Safari not support negative look behind regex expressions, which we use in our syntax highlighter..

https://developer.apple.com/documentation/safari-technology-preview-release-notes/stp-release-161#JavaScript

@rudolfs are you able to update safari to version 16.1 or maybe to the latest to see if this fixes it?

**Comment by sebastinez** [comment]
In case this fixes it, maybe we could see a way to avoid loading the syntax highlighting on safari browsers < v16

**Comment by rudolfs** [comment]
I think I would have to upgrade to macOS Ventura. Doesn't seem like there's a safari update for macOS Monterey.
