### ISSUE TITLE
Binary files show up as empty files in diffs

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#1039]
<img width="875" alt="Screenshot 2023-09-19 at 10 55 17" src="https://github.com/radicle-dev/radicle-interface/assets/158411/007f9940-847a-4964-887a-b7168fa2989a">

**Comment by sebastinez** [comment]
This is a libgit2 issue that don't detect binaries as they should in diffs.
@FintanH created a reproducible and wrote this issue on git2-rs https://github.com/rust-lang/git2-rs/issues/991
If this gets fixed eventually this issue should be solved.
