### ISSUE TITLE
Enforce signing off by contributors

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#11]
We should since it's required to sign off ones commits, enforce that the commits from future contributions are signed off by its authors.

I propose to create GitHub action, to do so. (In the future a Radicle Action? 😎)

**Comment by cloudhead** [comment]
Yes, I really want this!

**Comment by sebastinez** [comment]
To complete this we could install the [DCO Bot](https://github.com/apps/dco) that enforces signed off commits on all PR.
It's not the independent solution I want but its something to start with, we can later eventually built something in Radicle Upstream itself

**Comment by cloudhead** [comment]
Yeah that's fine for now, done!
