### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#146]
It would be good to start collecting some analytics on the web app in a privacy-preserving manner.

One popular open source solution is https://github.com/plausible/analytics which we can self host or pay to host. It doesn't store IPs and doesn't use cookies.

**Comment by sebastinez** [comment]
Oh thats sounds nice, and seems like really easy to implement and nice UI.
I think to start we can let them host it, (we can have 2 free months) and later we can host it ourselves?
The self hosting solution comes with a docker container which we can spin up on any VPS, and eventually bind it to some subdomain? stats.radicle.network perhaps?

**Comment by cloudhead** [comment]
Yeah, good idea.
