### ISSUE TITLE
[Temperature Check] Svelte web3 package

### ISSUE THREAD

**Issue by deckardkrug** [radicle-dev/radicle-interface#149]
Recently I have been thinking about creating a svelte package for web3 interactions. 
This issue is a request for feedback on this idea and to see if this would be useful for future iterations of the `radicle-interface` project. 

Some points that I like to see included in this package are:
- gnosis safe interactions
- ceramic network interactions
- interactions using wallet connect v2
- Sign in with Ethereum

**Comment by sebastinez** [comment]
Hey @deckardkrug.

Sounds like something really interesting.
As far as I'm concerned a package with the features you mentioned sounds like something that `radicle-interface` surely could benefit from..
I'm not quite sure how much benefit one could have from implementing gnosis, ceramic and wallet connect interactions over using the already provided SDKs.

Eventually you already thought about that, but the whole session management part, eg. [Sign in with Ethereum](https://github.com/spruceid/siwe) could be something interesting to implement in a Svelte way.

**Comment by deckardkrug** [comment]
@sebastinez happy to hear that.

With regard to the gnosis, ceramic and wallet connect sdks I was thinking about the svelte store management only - in addition to some helper methods.

> [Sign in with Ethereum](https://github.com/spruceid/siwe) could be something interesting to

Yes I have thought about that and I agree with you. It would be a great addition.

**Comment by sebastinez** [comment]
> There are only two hard things in Computer Science: cache invalidation and naming things.

hmm not a great name thinker myself.. :sweat_smile: 
Maybe some reference to Svelte?

If you want to chat more about the package please feel free to [join our Discord Server](https://discord.gg/dZK4TxaU2v), seems like a better place than our GH issues.

**Comment by cloudhead** [comment]
We looked for something like this before starting the project, mainly for connecting to wallets. It's definitely interesting, though at this point I'm not sure it would be worth switching to unless it also had additional wallet support, eg. ledger, coinbase wallet etc.

I'd call it something straightforward like `web3-svelte`.

**Comment by deckardkrug** [comment]
@sebastinez thank you, I am going to do that.
But first I would like to know if there are alternatives to Discord - i.e. is the Matrix channel used?

@cloudhead I agree with you that it would probably not make much sense to switch - I was just thinking about future iterations. Sadly `web3-svelte` is already taken as a npm package.

**Comment by deckardkrug** [comment]
I am going to move to [matrix](https://matrix.radicle.community/), therefore closing this issue.

Thank you for your feedback!
