### ISSUE TITLE
Add seed avatar from radicle self in seed page

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#156]

**Comment by sebastinez** [comment]
@cloudhead Would like to sync with you wrt to this issue, please let me know when you are available.

**Comment by sebastinez** [comment]
We'll eventually add a identity to the seed node where the avatar will be stored, but for now this is not high priority so will be de-prioritized

**Comment by sebastinez** [comment]
Hmm I think since we are now creating a profile for a seed node, it should be possible in the near future to create a ENS entry with an avatar or some way through the `IdentityDoc` to give a seed node an avatar.
Still not high priority but leaving this as reference

**Comment by cloudhead** [comment]
Yeah, basically it should show the org avatar that "owns" the seed.

**Comment by sebastinez** [comment]
Will close this issue for now since we are still pretty far away from the new orgs implementation and heartwood doesn't have node avatars
