### ISSUE TITLE
Improve the switching between states

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#160]
At the moment when switching branches, or views in the project component we don't have a desktop experience.
This can be solved by prefetching the information instead of going into a loading state.

**Comment by sebastinez** [comment]
A first step avoiding the moving of the page when the scrollbar pops in, is commit 9a9f4687ddd6f12a95828b0f3720927cddf70f78 on the `sebastinez/commit-detail` branch.
A next step would be to improve the loading states.

**Comment by sebastinez** [comment]
I think this issue can be solved with implementing more SSR, explained in issue #218

**Comment by rudolfs** [comment]
Going to close this in favour of https://github.com/radicle-dev/radicle-interface/issues/668. The general issue here is that we need to work on the routing/loading architecture to achieve the ux we want.
