### ISSUE TITLE
Support project names

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#171]
Instead of `/seeds/:seed/projects/:urn` we should also support `/seeds/:seed/projects/:name`, where `:name` is for eg. `nakamoto`. This will require support in `http-api` (it already is supported in `git-server`).

**Comment by sebastinez** [comment]
Ok have a PR in `http-api` for this, https://github.com/radicle-dev/radicle-client-services/pull/110
I'm not sure if we want to do `/seeds/:seed/projects/:urn` wouldn't it be nicer to have `/seeds/:seed/:urn` or `/:name` as suffix?
