### ISSUE TITLE
Cannot register radicle.eth name with Brave Wallet

### ISSUE THREAD

**Issue by gsaslis** [radicle-dev/radicle-interface#183]
I'm trying to test out the radicle.eth registration flow on Rinkeby. 

1. I visit https://app.radicle.network/registrations
2. I type in the name 
3. I click "Check" 
4. I see "The name babis is available for registration under account 4088 – Cb3a for 10.0 RAD."
5. I click "Begin registration" 
6. I see the following error: 

![Screenshot 2022-02-04 at 12 41 40 PM](https://user-images.githubusercontent.com/2420882/152515841-2e1abf29-2ebb-4479-9d52-ae8c02945a81.png)

**Comment by gsaslis** [comment]
A further data point: this worked just fine with metamask. 

The error above is with Brave Wallet.

**Comment by sebastinez** [comment]
I just tried to create a testnet org with the brave extension and it worked as expected.

Could you maybe pass me your current Brave version?I tried with v1.35.100 which seems to have a new extension, and in the settings `brave://settings/wallet` I selected Standard Crypto Wallet -> Brave Wallet (not the prefer others one..)

**Comment by sebastinez** [comment]
I'll close this issue for now, if there are new issues with the Brave extension we can reopen the issue.
