### ISSUE TITLE
Project listing should query seed nodes and add anchor information

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#186]
Currently the project listing in the `Profile` component queries the org subgraph for projects and their anchors, once done it checks for project info to render the project widgets.

The desired behaviour is to query the community or custom seeds (depending on the user/org), show this in the project listing and try to query anchor data from on-chain and add to the project widget metadata.

**Users:**
- For users we will need to query `/delegates/:id/projects` to get a listing of the projects of the user

**Orgs:**
- For now, if the org points at a public community node, we won't show any projects, not so if it points to a custom one.

This behaviour is implemented in the seed node pages, without the anchors adding, which are not possible since seed nodes don't have an ETH address atm.

**Comment by sebastinez** [comment]
@cloudhead wrt this issue I think with the PR #192 it seems like using the seed node defined by the user or org it's already solved right?
If a user defines a seed node in their ENS profile it will be used to get all the projects either way.

**Comment by cloudhead** [comment]
Yeah, what's missing though is we're still just quering _all_ projects of the seed, we should query only the user's.

**Comment by cloudhead** [comment]
Done.
