### ISSUE TITLE
Page loads to blank

### ISSUE THREAD

**Issue by codemaster138** [radicle-dev/radicle-interface#2]
I tried loading up the web interface, and this is what I saw:

<img width="1440" alt="Screenshot 2021-04-15 at 22 25 43" src="https://user-images.githubusercontent.com/43313420/114933937-911f3c80-9e39-11eb-9407-ad9d0b523020.png">

Am I missing something (Running latest chrome dev under MacOS 11.3 on MacBook Pro 13" Silicon)

**Comment by xla** [comment]
Did you run the build step with `npm build`? Also check the browser console for errors and report them back if you find any.

**Comment by codemaster138** [comment]
@xla I am not running it locally, I just opened app.radicle.network. I checked the console, but there are neither errors nor warnings. I also checked the sources, and a script that looks very much like compiled svelte code was loaded...

I'll try building this myself to see what happens

**Comment by cloudhead** [comment]
Yeah this is a known issue, due to relying on metamask.

**Comment by codemaster138** [comment]
Do we know the cause of the problem (at least a bit more specificly)

**Comment by codemaster138** [comment]
@xla @cloudhead Update: It seems to be happening in development too

**Comment by codemaster138** [comment]
Is there any known workaround to this?

**Comment by cloudhead** [comment]
> Is there any known workaround to this?

Install the metamask extension or use the Brave browser. Then it should work.

> Do we know the cause of the problem (at least a bit more specifically)?

Yeah, currently the code just tries to use `window.ethereum` and if it's not there it bails. This app is not meant to be used yet, it's a work in progress.

**Comment by cloudhead** [comment]
Fixed in master branch.
