### ISSUE TITLE
Improved peer selector

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#203]
It would be cool if the peer selector:
* Showed the peer name next to the id, eg. `cloudhead <peer-id>`
* Showed whether the peer was a delegate or not for the project, eg. `cloudhead <peer-id> [delegate]`

**Comment by cloudhead** [comment]
The former can be done like this: https://github.com/radicle-dev/radicle-client-tools/blob/master/common/src/project.rs#L160

**Comment by cloudhead** [comment]
Taking care of this on the server side.

**Comment by sebastinez** [comment]
Okay that's cool.
Was working on an implementation similar to the PR you created on `radicle-client-services`
Will use the new remotes info to improve the selector

**Comment by cloudhead** [comment]
Nice! I think I would show a badge with secondary color that says `delegate` to the right, eg. `<name> <peer-id> [delegate]`
