### ISSUE TITLE
Issue minor bugs

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#240]
There's a few things I noticed with issues that need a fix. I'm going to be keeping a list here.

* [x] URL does not update when user toggles between Open and Closed filters
* [x] Issue list isn't sorted, it should be sorted by timestamp descending
* [ ] #323
* [x] Make `labels` in `IIssue` interface not optional

**Comment by sebastinez** [comment]
Fixing some of the issues here
https://github.com/radicle-dev/radicle-interface/pull/245

**Comment by sebastinez** [comment]
> URL does not update when user toggles between Open and Closed filters

@cloudhead This could be done with a search query to not collide with the patch id e.g.
`/seeds/seed.sebastinez.dev/rad:git:hnrknh95r6scxqe45affa6xknqwydg8aj688o/issues?state=open`

wdyt?

**Comment by sebastinez** [comment]
Here an idea on the mobile view for issues, it is more like the GitHub issue view, but it feels like it works better for mobile

<img width="412" alt="Bildschirmfoto 2022-06-22 um 11 40 30" src="https://user-images.githubusercontent.com/7912302/174997724-414f4733-d8fe-4c14-9a70-b7cac76bfe2c.png">
<img width="1781" alt="Bildschirmfoto 2022-06-22 um 11 41 14" src="https://user-images.githubusercontent.com/7912302/174997898-eb826ae5-c0f7-4b1e-8ec4-68022ed9d357.png">

**Comment by sebastinez** [comment]
@brandonhaslegs If you have a minute I would also like your opinion on the issue view, desktop and mobile.
I think the current way we are doing it, does not work well on mobile, but we also don't want to go the GitHub way.
Here you can see the current way of the issue listing and detail
Any ideas?

**Comment by brandonhaslegs** [comment]
@sebastinez Let's talk about it next week.
