### ISSUE TITLE
Testing strategy

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#241]
We should define the scope we want to test in integration vs component testing (I don't mention E2E here on purpose since in our E2E tests we stubbed all responses and never hit a real server which equals to integration testing).

While integration testing allows us to traverse the application and test navigation, component testing allows us to mount a component in isolation and check all the possible edge cases and possible regressions, and unit testing goes one step further to just individual functions on their correctness.

**Integration testing `npm run test:e2e` eventually should be `npm run test:integration`**
- Connection through mocked Web3Provider
- Navigation through different URLs (e.g. the project pages, commits, issues, patches, etc.)
- Assert the URLs we're hitting and that they update correctly, when state changes
- Assert the least amount of display logic (we should leave that to component testing)
  If we are able to navigate to the correct URL and get the correct props, we shouldn't need to assert every piece of text.

**Component testing `npm run test:components`**
- Assert the correct rendering
- Test that the state of the component updates accordingly where applicable.

**Unit tests `npm run test:unit`**
- Util functions
- Classes (static and methods)

I'll keep updating this issue.
P.S.: Testing is not my expertise so any feedback is welcome.

**Comment by sebastinez** [comment]
@rudolfs Feel free to chime in here, probably there is some missing scenario or something that is in the wrong category.

**Comment by rudolfs** [comment]
@sebastinez yeah, I have thoughts on this, but would prefer to discuss this via a call first.

**Comment by sebastinez** [comment]
Closing this issue, since we are aligned on the strategy and there is nothing to fix here
