### ISSUE TITLE
Fixes for "Clone" popover

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#247]
- [x] close it when you click anywhere outside of it.

---

- [x] Fix the copy icon gradient overlay (it overlaps its container)
<img width="91" alt="image" src="https://user-images.githubusercontent.com/4406983/175994257-f3b56382-82d3-47e0-89e6-e65fcdf990cb.png">

---

- [x] Include `git clone` command in the copied content (to match the `rad clone` included in the rad command) 
<img width="374" alt="image" src="https://user-images.githubusercontent.com/4406983/175993613-2a08b809-4012-4903-97db-cd0cea692603.png">

---

- [x] maybe close it when you click the copy icon?

**Comment by cloudhead** [comment]
Looks fine for me, so must be a browser issue:
<img width="357" alt="image" src="https://user-images.githubusercontent.com/40774/176873568-92ca5fff-73c8-4b81-b1f7-70b0a7191b0e.png">

**Comment by brandonhaslegs** [comment]
Yep it's only like this in Safari (the modern Internet Explorer 😜)

**Comment by sebastinez** [comment]
PR #291 should fix all the points, still looking for the culprit with Safari, no luck so far.

**Comment by rudolfs** [comment]
This can be closed, right @sebastinez?

**Comment by sebastinez** [comment]
Yeah should have been closed automatically, but PR was closed instead of merged, will close it now
