### ISSUE TITLE
Change "at" to "on" on Commit page

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#248]
"at" isn't correct English. Should be "on"

<img width="530" alt="image" src="https://user-images.githubusercontent.com/4406983/175996135-aa803bb3-e79c-4d2c-91e5-5081351e503c.png">

**Comment by brandonhaslegs** [comment]
Ah cool, what's the plan for the relative date formatting? Does it start with seconds, then move to minutes, hours, days, and eventually just change to showing the date? That's what I would expect. And hovering over the relative timestamp shows the sepcific date with timezone?

**Comment by sebastinez** [comment]
> Ah cool, what's the plan for the relative date formatting? Does it start with seconds, then move to minutes, hours, days, and eventually just change to showing the date? That's what I would expect. And hovering over the relative timestamp shows the sepcific date with timezone?

Yes that's exactly how it'll work.

**Comment by sebastinez** [comment]
PR #246 closes this issue
