### ISSUE TITLE
Add context tooltip to "Verified" badge

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#249]
The UI says this commit is verified but I'm not sure what that means. Maybe add a simple 1-liner that appears when you hover over the verified badge.

<img width="506" alt="image" src="https://user-images.githubusercontent.com/4406983/175996322-9410ca2d-daa8-4bb9-b736-b1785bfebef5.png">

**Comment by sebastinez** [comment]
This issue will be fixed with PR #230 

The end result will look like.
<img width="251" alt="Bildschirmfoto 2022-06-27 um 20 17 38" src="https://user-images.githubusercontent.com/7912302/176008926-b5789d91-61dd-4ea8-a813-5aee9b6d17cf.png">

**Comment by cloudhead** [comment]
If you want to try to get that over the finish line @sebastinez would be great, I was having trouble getting one of the tests passing.
