### ISSUE TITLE
Show projects from seed nodes in search results

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#250]
Show search results for projects
<img width="592" alt="image" src="https://user-images.githubusercontent.com/4406983/175996780-db31c75f-3820-41e0-98cc-95054d349862.png">

**Comment by cloudhead** [comment]
Yeah this requires a network architecture that we don't have right now, but we will get there eventually.

**Comment by sebastinez** [comment]
Okay, PR #327 does a fetching of all listed seed nodes in `config.seeds.pinned` and shows the projects on all the seed nodes it has been found by name or URN and let's you navigate to it.
If a project has the same name as a registered ENS name it lets the user choose
