### ISSUE TITLE
Expand name search to be more dumb-user-friendly

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#251]
Show .eth and .radicle.eth search results (brandonhaslegs.eth and brandonhaslegs.radicle.eth both exist, but searching brandonhaslegs shows no results)
<img width="618" alt="image" src="https://user-images.githubusercontent.com/4406983/175997027-b7efe7fd-77b7-40ea-b7a7-a1a97665e5b4.png">

**Comment by sebastinez** [comment]
Interesting, and what should we do if we encounter both addresses, show a listing? Where the user can select the address of his/hers choosing?

The other thing we could do is to debounce the search query some seconds and show a listing of possible addresses the user can select from, similar to the GitHub search field.
<img width="564" alt="Bildschirmfoto 2022-07-15 um 14 47 32" src="https://user-images.githubusercontent.com/7912302/179225906-9af63f13-10ca-4205-a929-48275953159d.png">

**Comment by cloudhead** [comment]
Yeah I'd just show a listing if there's more than one result.
