### ISSUE TITLE
Remove or fix orgs page

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#252]
I thought Radicle removed Orgs. If so, remove the page and nav item from the header.

If not, this page should be fixed. It currently loads a bunch of orgs and then removes all the orgs leaving you with a blank page.

![orgs-bye](https://user-images.githubusercontent.com/4406983/175999292-1d0b2033-3045-4c6e-bb2b-bcb44f7a99e2.gif)

**Comment by cloudhead** [comment]
WTF I've never seen this.

**Comment by cloudhead** [comment]
Ah it's an issue with the per *second* limit, weird. We should just remove the page anyway.

**Comment by sebastinez** [comment]
PR #289 has removed the org listing for now
