### ISSUE TITLE
Explain what radicle.eth names are or what they do

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#253]
If it's going to be one of two items in a main navigation, probably should explain why you'd want to register a name at all. Don't think it need to be overthought too much, I think a line of text under "Register a radicle.eth name" should be enough.

<img width="761" alt="image" src="https://user-images.githubusercontent.com/4406983/175999553-01ed6ad5-9024-4266-8d8d-b7437e5b8614.png">

**Comment by sebastinez** [comment]
There is a good text in https://radicle.xyz/blog/integrating-with-ethereum.html

> 🌐 Global names
> 
> Today's hosted platforms benefit from the network effects that come with centralized server-side data hosting. Peer-to-peer systems lack this global namespace and the discoverability that comes with it. In Radicle, you'll be able to register unique names with our ENS registrar, under the radicle.eth domain (e.g. cloudhead.radicle.eth) for your profile or organization. This will be a name that other users can use to recognize you not only within the Radicle network, but also the global Ethereum network. These names are interoperable and self-sovereign usernames that resolve to an Ethereum address.

I'm thinking we could add some TL;DR e.g.:
> Register a unique name with our ENS registrar, under the radicle.eth domain (e.g. cloudhead.radicle.eth) for your profile or organization.

**Comment by brandonhaslegs** [comment]
Wonder why we don't only use .eth names. Like what is the benefit of a radicle.eth name? Do you get something more special when you have a radicle.eth name? Does it have any benefits over .eth?

**Comment by sebastinez** [comment]
In feature set you get the same as a .eth name, maybe a bit cheaper since you won't have to pay a registration fee only gas.
I see it as a alternative top level domain, maybe to differentiate ones .eth profile for ETH activities from a .radicle.eth identity for code collaboration, funding, etc.

**Comment by sebastinez** [comment]
In general true, but I can also see a use case where one would want to differentiate ones identities.
Similar to have multiple email domains or websites according to its use case.

@cloudhead wdyt?

**Comment by cloudhead** [comment]
Yeah I think there's two reasons mentioned above:

1. It's free forever (vs. .eth which requires yearly fees)
2. For orgs, it may be useful to separate the "code" identity from the "general" identity. Eg. `nike.eth` for the general identity, and `nike.radicle.eth` for the dev team.

**Comment by cloudhead** [comment]
There's also a benefit for us (which can become a user benefit), where we can do airdrops and stuff like that to all radicle users.
