### ISSUE TITLE
explain what "not anchored" means in the project nav

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#255]
<img width="186" alt="image" src="https://user-images.githubusercontent.com/4406983/176006023-a0f1a829-caf7-4fa1-aa89-1796cb85e69d.png">

Some ideas:
- [ ] clicking on it goes to the anchoring flow?
- [ ] perhaps remove it if anchoring isn't a thing anymore
- [ ] add "not allowed" cursor, like the issues button if the feature isn't launched yet
- [ ] definitely remove the "pointer" cursor, because clicking it doesn't do anything
- [ ] add tooltip to it explaining what "not anchored" means

**Comment by cloudhead** [comment]
I think we should hide the widget completely behind a feature flag until anchoring is re-visited.

**Comment by brandonhaslegs** [comment]
Cool I will create another issue for that.
