### ISSUE TITLE
Add themeing (light/dark mode)

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#256]
The app is just in dark mode now, but it's pretty standard to have light and dark mode in apps. We buit the design system to handle this really easily, so could just use that.

**Comment by sebastinez** [comment]
I fully agree on the having two themes (dark/light), not sure on the design system part, since we always worked on a very own styling. Maybe something you could talk about with @cloudhead?

**Comment by brandonhaslegs** [comment]
Oh I just meant we could grab the way we did theming from the design system in Upstream maybe.

**Comment by cloudhead** [comment]
Yeah, I think this is very low priority but would be nice some day!

**Comment by brandonhaslegs** [comment]
Of course. I bet it'd be pretty easy though. @efstajas has done it a few times on various web apps.
