### ISSUE TITLE
On "Register" page, make "radicle name" text field same height as "check" button

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#258]
It's currently 1px smaller

<img width="1294" alt="image" src="https://user-images.githubusercontent.com/4406983/176008463-5311dbac-50d3-4e00-91fe-853b135eee96.png">

**Comment by sebastinez** [comment]
It seems this has been already fixed, at some point.

<img width="1704" alt="Bildschirmfoto 2022-09-25 um 22 13 22" src="https://user-images.githubusercontent.com/7912302/192163309-ed4ec827-506f-44cd-aded-0a9faadd0dfd.png">

I'll close it for now.
