### ISSUE TITLE
Close overlay menus when clicking outside

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#259]
- [ ] Connect wallet
<img width="684" alt="image" src="https://user-images.githubusercontent.com/4406983/176138244-324cf743-85d9-4fd0-a22e-a6074c679baf.png">

---

- [ ] Register a name overlay
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/4406983/176000440-d6539372-5908-4fa3-a6e5-33342f513397.png">

---

- [ ] Clone a project
<img width="438" alt="image" src="https://user-images.githubusercontent.com/4406983/176000609-4ce67849-4448-4089-83dc-9c439c46ea2c.png">

---

- [ ] Peer overlay
<img width="598" alt="image" src="https://user-images.githubusercontent.com/4406983/176000798-7890868e-8666-4666-963e-da0f40b7b0ba.png">

**Comment by sebastinez** [comment]
#313 closes this issue
