### ISSUE TITLE
Update tooltip text on issues to something more explanatory

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#260]
Not supported seems like they might be supported if I do something, or in another version of the app. Suggestions:

- Issues • Coming soon!
- or maybe just remove it until the feature launches

<img width="189" alt="image" src="https://user-images.githubusercontent.com/4406983/176013443-7e4edbd5-c565-4fce-aa73-3268e9c971f5.png">

**Comment by sebastinez** [comment]
@brandonhaslegs this hasn't found it's way into master yet, would leave it open, until solved
I'm thinking maybe the best way would be to simply not show the issues button when not supported, since a seed node operator could use a version before issues due to some reason.

**Comment by cloudhead** [comment]
Hmm, yeah I guess we can just not show it on projects that don't support it.
