### ISSUE TITLE
Unify form fields

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#261]
Choose either dashed or solid. It's unclear why one is dashed and one is solid. I'd recommend going with solid, as dashed feels a bit like it's disabled or a placeholder.

<img width="277" alt="image" src="https://user-images.githubusercontent.com/4406983/176009491-02641c86-6522-4d6c-8b03-8ee92903596d.png">
<img width="458" alt="image" src="https://user-images.githubusercontent.com/4406983/176009520-4a3b7c4f-4b0b-4436-9170-4088c941912d.png">

**Comment by sebastinez** [comment]
Added the question label, so we can keep track on where a decision is needed.

**Comment by brandonhaslegs** [comment]
Closing because there's only one field after Eth features are removed.
