### ISSUE TITLE
Add tooltip to "Edit" and "Transfer" buttons

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#262]
When wallet is not connected, or wallet is connected and you are not the owner of the name, the "Edit" and "Transfer" buttons are disabled, but there's no context for them. Need a tooltip explaining why they're not clickable.

**Comment by cloudhead** [comment]
Similar thing with the issue button etc. I tend to prefer not to hide/show buttons, but rather disable them so that the user knows they are there vs. the user searching for it because he saw it somewhere.

**Comment by brandonhaslegs** [comment]
Cool, I think they could look even more disabled, and there could be a tooltip explaining why you can't click them.

**Comment by cloudhead** [comment]
Yeah. Also I think one of them can be removed (transfer) because we haven't implemented that actually.
