### ISSUE TITLE
Fix code added/removed highlights

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#266]
The code highlights (the slight red and green background colors) should go all the way through the code block, instead of just highlighting the line numbers

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/4406983/176033490-0919de59-b1ce-435c-947a-4495bda9b883.png">

**Comment by brandonhaslegs** [comment]
I think that would be a fine solution for now.

**Comment by cloudhead** [comment]
The gutter is a distinct element and the font color isn't the same, so I wouldn't remove the background from there. I think we can just wait until we can do it properly and leave it as is for now.

**Comment by sebastinez** [comment]
I put the hold label on this issue, so we can revisit it once it's possible for the web client to pull this off.
