### ISSUE TITLE
Unify height of header items

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#269]
40px
<img width="300" alt="image" src="https://user-images.githubusercontent.com/4406983/176267579-6fab1dbc-4190-4929-b5ad-e1d304b9be25.png">

42px
<img width="278" alt="image" src="https://user-images.githubusercontent.com/4406983/176040980-9b3a29bc-2494-4710-bec3-943680e1e0ff.png">

43px
<img width="363" alt="image" src="https://user-images.githubusercontent.com/4406983/176041027-fb02f555-4e37-43e2-b222-aea1ed42bd81.png">

**Comment by rudolfs** [comment]
Is this still relevant? Just inspected all of the elements on master and they were consistently `40px` high.

<img width="303" alt="Screenshot 2022-08-25 at 15 57 22" src="https://user-images.githubusercontent.com/158411/186684567-c9fd7fe8-380d-4ee8-9bf0-fa2f4bb02c31.png">
<img width="311" alt="Screenshot 2022-08-25 at 15 57 28" src="https://user-images.githubusercontent.com/158411/186684583-69799303-d900-4380-8e93-a4dc94e1562b.png">
<img width="358" alt="Screenshot 2022-08-25 at 15 57 32" src="https://user-images.githubusercontent.com/158411/186684592-c8c7e41d-1c3f-461f-9f68-f49f696b44ee.png">
<img width="1728" alt="Screenshot 2022-08-25 at 15 57 41" src="https://user-images.githubusercontent.com/158411/186684598-b7051fc8-8cdb-4476-b5cd-53e8ff31153a.png">

**Comment by rudolfs** [comment]
@brandonhaslegs bow I also wonder about all the other buttons, whether they're the right height?

<img width="734" alt="Screenshot 2022-08-25 at 16 15 58" src="https://user-images.githubusercontent.com/158411/186690841-b6d29195-591c-428f-85de-70f5f964265c.png">
<img width="922" alt="Screenshot 2022-08-25 at 16 16 10" src="https://user-images.githubusercontent.com/158411/186690858-10a2f787-bda7-41b0-83f5-0a38897ec0e1.png">
<img width="1148" alt="Screenshot 2022-08-25 at 16 16 30" src="https://user-images.githubusercontent.com/158411/186690865-be3319a9-dd52-4f4b-b2ea-169e07649abe.png">
<img width="740" alt="Screenshot 2022-08-25 at 16 17 32" src="https://user-images.githubusercontent.com/158411/186690868-0d09516b-1546-4244-9ebb-6701e93c354c.png">
<img width="1128" alt="Screenshot 2022-08-25 at 16 18 15" src="https://user-images.githubusercontent.com/158411/186690873-dfb4beb9-6f69-42a7-81cd-6d4679a8af87.png">
<img width="1109" alt="Screenshot 2022-08-25 at 16 19 50" src="https://user-images.githubusercontent.com/158411/186690878-7140ecd8-a9f4-45b1-b772-fb0254f38edf.png">
<img width="907" alt="Screenshot 2022-08-25 at 16 20 49" src="https://user-images.githubusercontent.com/158411/186690880-dc1707f2-6ff3-4dd4-8e73-c60ec23ccca6.png">
<img width="880" alt="Screenshot 2022-08-25 at 16 21 37" src="https://user-images.githubusercontent.com/158411/186690881-b43d720a-1270-4f59-8c2f-1bd47716280c.png">
<img width="398" alt="Screenshot 2022-08-25 at 16 15 53" src="https://user-images.githubusercontent.com/158411/186690827-cd251ea1-07a5-4a31-b45d-a1432aa2994f.png">

**Comment by brandonhaslegs** [comment]
I think everything but the project nav looks right. Dunno where 34px comes from.
