### ISSUE TITLE
Rethink the use of blue in the app

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#273]
Look, I get that you could consider this just an opinion, but I think it'd be really smart to not use a color to differenciate UI stuff.

- Blue is the most common link color, and it doesn't always mean link in this case
- Blue on dark blue is kinda hard on the eyes
- I don't really get the decision-making for using blue. sometimes it's titles, sometimes it's meta data, sometimes it's a placeholder in input fields, it just feels really haphazard

I'd suggest just using a `level` variation to distiguish titles or other UI elements, instead of blue.

**Comment by brandonhaslegs** [comment]
Btw here's a contrast test for the blue and the dark blue background color. Maybe that's interesting. 
<img width="730" alt="image" src="https://user-images.githubusercontent.com/4406983/176044714-91df1e43-02aa-4dcd-baae-b9a0ef5dd671.png">

**Comment by cloudhead** [comment]
It's basically used as an alternate color to differentiate from white in certain situations. Happy to revisit this where it doesn't make sense.

**Comment by brandonhaslegs** [comment]
Cool, I'd like to just try something out, see what I come up with.

**Comment by sebastinez** [comment]
I'll close this issue since we'll be doing an entire rebranding of the web client.
