### ISSUE TITLE
Fix 🔓 emoji usage

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#275]
It's unclear what the lock emoji means. It only appears sometimes, but doesn't seem to correlate with a meaning (being anchored or not).

Does not have lock emoji
<img width="745" alt="image" src="https://user-images.githubusercontent.com/4406983/176144766-92fedc22-37aa-4710-abdc-18b03363804f.png">
Is not anchored
<img width="363" alt="image" src="https://user-images.githubusercontent.com/4406983/176144850-21ffd2a1-9e37-4d58-86eb-673cac357dd6.png">

Does have lock emoji
<img width="729" alt="image" src="https://user-images.githubusercontent.com/4406983/176144919-22f17664-d0d7-4e43-9edf-6a64a8fbca59.png">
Is also not anchored
<img width="358" alt="image" src="https://user-images.githubusercontent.com/4406983/176144973-562ed3e3-4461-4ba7-98eb-a3f70df888f9.png">

So what does the emoji mean? Both projects are not anchored, but one shows a lock emoji on hover and the other doesn't.

Also just discovered that clicking the "not anchored" button, shows a new lock emoji with a string next to it. Is this the last anchored state? What is anchoring after all? Maybe a tooltip could help here.
<img width="475" alt="image" src="https://user-images.githubusercontent.com/4406983/176145567-75608aa9-75b5-4e66-b397-77375b754d4d.png">

**Comment by cloudhead** [comment]
Aye, this needs to be revisited, and I wanted to add a very extensive popup that explains all the states, but since this feature is not really used and de-prioritized, I'd rather hide the badge completely behind a feature flag for now.

**Comment by sebastinez** [comment]
I'm closing this since we'll be hiding it with PR #295 for now
