### ISSUE TITLE
Unify font sizes

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#279]
Usually you can get by with just three sizes, small, regular, and large. Also these should be standardized with css variables

**Comment by cloudhead** [comment]
Might need 4, but I'm supportive.

**Comment by rudolfs** [comment]
I think this is resolved. Albeit we have a bit more than 3, but they're CSS variables now.

```
--font-size-tiny: 0.75rem;
--font-size-small: 0.875rem;
--font-size-regular: 1rem;
--font-size-medium: 1.25rem;
--font-size-large: 1.75rem;
--font-size-huge: 2rem;
```

`large` and `huge` are only used in a couple of places.
