### ISSUE TITLE
Make issues empty state more clear

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#281]
Instead of just saying "no results matched your search" (I didn't search anything, I just opened the issues page) there should be a real empty state here. And even if this is the state when you filter to the point where there are no issues to be shown, this text is oddly generic. Suggestions:

When there are no issues at all: **There are no issues on the project yet.**

When you have filtered or searched the issue list and there are no results: **No issues match your search.**

<img width="294" alt="image" src="https://user-images.githubusercontent.com/4406983/176448913-14a0073e-da4e-4fe2-99c6-2d076f2c3762.png">

**Comment by cloudhead** [comment]
Perhaps with an emoji also, eg. we do this for files that don't exist:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/40774/176868319-1cf2169c-3d78-4922-a112-b20b20e15147.png">
