### ISSUE TITLE
Allow user to customize monospace font

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#282]
The default monospace font is … jarring. Would be nice to be able to set something more thoughtful and also to allow users to customize it to whatever they are most comfortable with.

**Comment by cloudhead** [comment]
This is already configurable through your OS, that's why I've set it to `monospace`.. I think this is better than choosing the font for users who are used to a certain monospace font already (the one they use in their editor).

**Comment by cloudhead** [comment]
Ok this must be a linux thing. The font I've been using everywhere for monospace is JetBrains Mono (https://www.jetbrains.com/lp/mono/). I'd be ok with setting that as the default for now, and later allowing developers to change it. For linux users it's still useful to be able to set it to `monospace` as that allows you to have the same font in your editor as well as on the web without requiring the font to be available as an option.

**Comment by brandonhaslegs** [comment]
Yep I think one of the settings would be "System".
