### ISSUE TITLE
Make it possible to connect a wallet on mobile

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#287]
Not possible at the moment but I've definitely seen it done in other web3 apps.

![image](https://user-images.githubusercontent.com/4406983/176916628-cbfbf5c2-c9cf-47e2-bba4-7f66ebc5aa06.png)

**Comment by cloudhead** [comment]
Yeah good point, I think it requires links that open apps on your phone.

**Comment by brandonhaslegs** [comment]
I think @efstajas made this work for rad.lol?

**Comment by efstajas** [comment]
On rad.lol I just used the official WalletConnect SDK & connection modal, which implements all of this out of the box — platform-detects iOS to display the app-specific links, on Android shows a single "Connect" link, and on desktop a QR code.

I did look into it however before deciding implementing it custom wasn't worth it — you can get a list of wallets registered with WalletConnect App Registry through this API: https://registry.walletconnect.com/api/v1/wallets?entries=5&page=1 Then, for the connection modal on iOS, it's a matter of displaying all these apps and triggering the universal link contained in the API response, with `/wc?uri=<connection uri>` at the end, e.g. `https://link.trustwallet.com/wc?uri=wc%3A7c8c54cd-c31e-4d4d-93d7-d0ad7e1fb85b%401%3Fbridge%3Dhttps%253A%252F%252Fx.bridge.walletconnect.org%26key%3Ddb699e6bd6e96ee9c4a8cf53f499b30c9741698a51b3dbcec5cc53c4c40f0952`.

If you think it's worth building a custom UI for this, I'd be happy to give it a go sometime soon after wrapping up the next Workstreams milestone. Another option would obviously be just using the WalletConnect SDK.

**Comment by sebastinez** [comment]
Okay according to what we talked over Discord (https://discord.com/channels/841318878125490186/856904179820920833/1069181291284660286) we'll remove all eth functionality from the web app, so this issue is no longer relevant
