### ISSUE TITLE
WalletConnect support

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#29]
Currently, the app only supports Metamask, through `window.ethereum`. We'd like to support WalletConnect 1.x (and later 2.x) to be able to use mobile wallets such as Rainbow (https://rainbow.me/).

Since we currently  use Alchemy as a `Provider`, we only wish to integrate WalletConnect as a `Signer`. [There is also one place where we use an  EIP-712 signature][712], which we'd want to do via WalletConnect as well.

The goal is _not_ to only support WalletConnect, but to support _both_ Metamask and WalletConnect, with the "default" option being WalletConnect.

The implementation should be done in such a way that we can later support more signers, such as Ledger Nano without completely changing the architecture of the code. It goes without saying that the signer should be abstracted in such a way that the app logic shouldn't have to know what method is used for signing, once the user connects their wallet.

[712]: https://github.com/radicle-dev/radicle-interface/blob/master/src/base/registrations/registrar.ts#L181

## UI

From a UI point of view, we expect that when the `Connect` button is hit, a `<Modal floating>` is used to display the QR code to connect the mobile wallet. Underneath the QR code, we can display additional wallet options, eg. Metamask, Ledger etc. But basically, unlike Web3Modal, we want to display the QR code as a default, instead of first asking the user to choose how they want to connect. This removes one step for users using WalletConnect.

Besides this new modal, there should be no changes to the UI.

## Requirements

* If the user refreshes the app or comes back to it later, we should try to preserve the WalletConnect connection, so they don't have to reconnect every time. We currently do this for Metamask by storing a cookie in LocalStorage.
* There should not be any dependencies pulled in besides the walletconnect libraries.
* All error states should be handled gracefully, by showing a message to the user
* It should be easy to change what provider you use to connect to the app, eg. I should be able to switch from WalletConnect to Metamask after I've been connected with WalletConnect. For this, we should simply clear any kind of cookie when the user hits `Disconnect`.

## Notes

WalletConnect currently has two providers that could be used with `ethers.js` which we use: `Web3Provider` and [`EthereumProvider`][eth-provider]. The former is better supported, but comes with many additional dependencies, while the latter is much lighter. It would be preferred to use `EthereumProvider` due to its smaller dependency footprint, but if it turns out to be too unstable, we can consider using the `Web3Provider`.

The walletconnect libraries use a mix of ESM and UMD modules which can cause problems with our bundler. If it's not possible to import the libraries as npm packages, the pre-built releases can be included as minified javascript in `index.html`, and a wrapper typescript module can be used to expose them to the rest of the app.

Any configuration that is required by the implementation, eg. the bridge server address, should go in the `/src/config.json` file.

Part of the challenge here will be providing a clean abstraction for both Metamask and WalletConnect, such that we keep all wallet-specific code in one place, and not spread over the codebase. This may require moving some of the current Metamask integration code to a different place.

[eth-provider]: https://github.com/WalletConnect/walletconnect-monorepo/tree/v1.0/packages/providers/ethereum-provider

**Comment by Khay-EMMA** [comment]
- [ ] Implement walletconnect functionality
- [ ] Refactor walletconnect to use custom ethereum provider instead of the default client
- [ ] Show modal to choose which wallet connect
- [ ] Refactor config.ts and session.ts to accept multiple wallets
