### ISSUE TITLE
Fix broken compatible WalletConnect wallets

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#299]
And again it seems that the link to a compatible wallet listing for WalletConnect is broken.

The latest working link it seems is: https://explorer.walletconnect.com/registry?type=wallet

This edit should be made here: https://github.com/radicle-dev/radicle-interface/blob/cbbaadd3307bba182e8cc88a3a1279b0a42825f5/src/components/Modal/ConnectWallet.svelte#L56

**Comment by sebastinez** [comment]
Hmm yeah that would also be possible, but maybe we could also remove this compatible link altogether.

It seems that not even WalletConnect shows this link in their QR Code modal, maybe one can already suppose that enough Wallets have WalletConnect support?
<img width="300" alt="Bildschirmfoto 2022-08-03 um 16 57 52" src="https://user-images.githubusercontent.com/7912302/182640728-be287c90-e915-4628-8b96-ce7a64bf0e2c.png">

**Comment by cloudhead** [comment]
Heh you're right, let's remove, it'll also make the modal less tall.
