### ISSUE TITLE
Error button styles broken

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#302]
This is my fault. The button is also not functional, which may be also my fault? Not sure…

Hover:
<img width="789" alt="image" src="https://user-images.githubusercontent.com/4406983/182359700-5dddc0dd-a801-4f91-9fbb-1a2fa518b320.png">

Default:
<img width="774" alt="image" src="https://user-images.githubusercontent.com/4406983/182359766-cd1fd54b-2ae1-4872-91db-342163915968.png">

**Comment by rudolfs** [comment]
Can't reproduce this. Which browser did you use?

`master` on Chrome looks fine to me:

<img width="1840" alt="Screenshot 2022-08-22 at 13 35 52" src="https://user-images.githubusercontent.com/158411/185912234-f4bc5eb5-4508-49e7-bf93-3866ad1c1446.png">
<img width="1840" alt="Screenshot 2022-08-22 at 13 35 50" src="https://user-images.githubusercontent.com/158411/185912218-e85cb4ac-5b69-4490-a5ab-814c1bde0c96.png">

**Comment by brandonhaslegs** [comment]
Maybe @cloudhead fixed it…

**Comment by sebastinez** [comment]
I think this has been fixed with https://github.com/radicle-dev/radicle-interface/commit/01f7af357df22da246e654fd0475ed16d2077ab5
