### ISSUE TITLE
Height of project nav buttons should conform to standard heights. 32 instead of 34

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#346]
![image](https://user-images.githubusercontent.com/4406983/186914207-b396987f-4758-4bca-bac8-8e25f43d2bfd.png)

**Comment by sebastinez** [comment]
It seems like this was introduced with https://github.com/radicle-dev/radicle-interface/commit/22437fcf4f2aefd8da9849cb7a56a24fe0fc775d, before doing a PR, just checking if 32px (2rem) is the height we are all good with.
cc @cloudhead

**Comment by cloudhead** [comment]
Hmm, yeah, I think I was trying to fix something else and this broke.

**Comment by sebastinez** [comment]
Has been fixed by ff267620a6afc609e08cf5cb4775a5eda190f4cb
