### ISSUE TITLE
Remove "not allowed" cursor state from Patches nav

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#348]
<img width="326" alt="image" src="https://user-images.githubusercontent.com/4406983/187271917-82ad2ebe-4b11-434e-ac68-91dd4e8ed1e1.png">

These are set to "not-allowed" so it seems like you can't click on them.

**Comment by rudolfs** [comment]
It's because of a bug. I fixed it part of this refactor: https://github.com/radicle-dev/radicle-interface/pull/347.

**Comment by sebastinez** [comment]
Fixed by merging #347
