### ISSUE TITLE
Create a packaged version for local deployment

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#353]
To allow end users mount a local instance of the web client on their machines, we need to package the web client so it can be served with the execution of a single binary.

**Process**
1. End user downloads binary
2. Executes binary
3. A static file server is mounted
4. The default browser is opened at `http://radicle.local`

**Pending points to be defined**
- [ ] The binary would need a compiled version of the web client
- [ ] How would we allow users to navigate to `http://radicle.home` and show the locally served site on different OS 
- [ ] When should we compile the application?

**Versions**
I wrote a small config file for [binserve](https://github.com/mufeedvh/binserve) which can be our static file server, it is 🦀 and quick
https://github.com/radicle-dev/radicle-interface/tree/sebastinez/packaging

**Comment by rudolfs** [comment]
Would be interesting to investigate whether it's possible to bundle the server and assets into the same binary, à la https://github.com/peku33/web-static-pack.

**Comment by rudolfs** [comment]
Regarding using `.local`, from what I've read it shouldn't be used for pointing to services running on your localhost.
It's original purpose is [multicast-dns](https://www.rfc-editor.org/rfc/rfc6762):

>  To remedy this problem, this document allows any computer user to
   elect to give their computers link-local Multicast DNS host names of
   the form: "single-dns-label.local.".  For example, a laptop computer
   may answer to the name "MyComputer.local.".  Any computer user is
   granted the authority to name their computer this way, provided that
   the chosen host name is not already in use on that link.  Having
   named their computer this way, the user has the authority to continue
   utilizing that name until such time as a name conflict occurs on the
   link that is not resolved in the user's favor.  If this happens, the
   computer (or its human user) MUST cease using the name, and SHOULD
   attempt to allocate a new unique name for use on that link.  These
   conflicts are expected to be relatively rare for people who choose
   reasonably imaginative names, but it is still important to have a
   mechanism in place to handle them when they happen.

So if someone with a mac on your local network names their coputer "radicle", you're in trouble.

<img width="780" alt="Screenshot 2022-08-31 at 13 45 16" src="https://user-images.githubusercontent.com/158411/187671239-f96bf4b4-ef48-49d7-9e26-100ef6124922.png">

**Comment by rudolfs** [comment]
Another potential avenue to explore would be PWAs or "add-to-homescreen". Unfortunately [only chrome supports it](https://caniuse.com/?search=PWA) at the moment.

**Comment by cloudhead** [comment]
> Regarding using .local, [from what I've read](https://news.ycombinator.com/item?id=12578908) it shouldn't be used for pointing to services running on your localhost.

Yup, you're right, TIL. Perhaps we can use `radicle.home` then:

https://en.wikipedia.org/wiki/.home

**Comment by sebastinez** [comment]
Ok I looked a bit deeper than their abbreviation into PWAs.
And while I think we should support it, and allow users to install them.

I think for the censor resistant part we still should offer some bundled binary.

**Comment by rudolfs** [comment]
> And while I think we should support it, and allow users to install them, I still think for the censor resistant part we still should offer some bundled binary.

Not sure it makes sense to offer it if we will have some other way of installing it locally. We'd have to keep maintaining both, which is extra effort. I think we should make an informed decision and then stick with one approach.

**Comment by rudolfs** [comment]
Wonder if we couldn't get away with a bundled `radicle.html`? 🤔

**Comment by rudolfs** [comment]
And then there's [redbean](https://redbean.dev). 👹

**Comment by sebastinez** [comment]
It doesn't comply with the process defined here, but I think #478 deployed on IPFS, and pinned by end users on their local node is a nice first step to self hosting

**Comment by cloudhead** [comment]
Yeah it's pretty annoying. The simplest way for macOS and Linux though would be to ask the user to add an entry to `/etc/hosts`.

I remember an app that worked with `web3.local` with zero conf (I think), but don't remember what app it was, I think it was in the substrate days.

Alternatively there's mDNS, but seems like browsers don't all support it; but mDNS uses `.local`.

**Comment by rudolfs** [comment]
We discussed this in the last meeting, the consensus was that we'll try to automate deployments to IPFS first. And offer a convenient way to find what the address is of the latest deployment via the CLI.

**Comment by cloudhead** [comment]
Also investing in some kind of "version management" where you can update to the latest ipfs deploy manually. This can come after the mvp though.

**Comment by rudolfs** [comment]
> Also investing in some kind of "version management" where you can update to the latest ipfs deploy manually. This can come after the mvp though.

Could we just use [IPNS](https://docs.ipfs.tech/how-to/publish-ipns/#publishing-ipns-names-programmatically-with-js-ipfs) for this?

**Comment by sebastinez** [comment]
I think I'll close this issue in favor of a new issue related to implement IPFS deployment of the web client.
