### ISSUE TITLE
Emojis differ depending on which OS you're on

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#356]
It would be nice if the emoji assets would be the same regardless of which OS you're looking at the app from. A possible workaround is to use [Twemoji assets](https://twemoji.twitter.com/). We already implemented this in Upstream [[1]](https://github.com/radicle-dev/radicle-design-system/blob/main/Emoji.svelte)[[2]](https://github.com/radicle-dev/radicle-design-system/blob/main/scripts/install-twemoji-assets.sh), it would be quite easy to port it over.

macOS:

<img width="1840" alt="Screenshot 2022-09-01 at 16 50 27" src="https://user-images.githubusercontent.com/158411/187944583-250fb82a-1b21-4e86-b465-19880592cc19.png">

Windows:

<img width="1322" alt="Screenshot 2022-09-01 at 16 45 27" src="https://user-images.githubusercontent.com/158411/187944449-e2722a61-963f-47f5-95c9-bf70b4be444c.png">

Linux:

![Screenshot_from_2022-09-01_16-47-10](https://user-images.githubusercontent.com/158411/187944486-89feeced-a4a4-432d-bdf5-46cbe0a7c01d.png)

**Comment by rudolfs** [comment]
Another option would be to do it at the bundler level, e.g. vite/rollup.

**Comment by brandonhaslegs** [comment]
Windows doesn't render emojis? Are you kidding me

**Comment by rudolfs** [comment]
> Windows doesn't render emojis? Are you kidding me

I think it depends on the font, perhaps the font on that windows version didn't have the new emojis. 🤷

**Comment by cloudhead** [comment]
Yeah using tweemojis is probably a good idea, like we do in upstream.
