### ISSUE TITLE
Page transitions fade in

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#364]
I think this would also be possible with `svelte-routing` but I stumbled upon it with `tinro`.
We could make the transitions between the pages a bit more subtle, it seems less ragged, I went with 200ms for now, but could be changed too.

https://user-images.githubusercontent.com/7912302/188477858-6cc74a55-14cd-4d63-8980-17d81eb0b68b.mov

Please let me know what you think from a design and UX standpoint cc @cloudhead @brandonhaslegs @rudolfs

**Comment by brandonhaslegs** [comment]
Looks good!

**Comment by efstajas** [comment]
The sample transition looks great! Simple & smooth. My only thought was: without knowing much about the internals of this app, are all the route chunks loaded ahead of navigation already or is the fade-in of the new route deferred until some chunk was fetched? If the latter, I'd be thinking about fading in a spinner _only if_ the new route loading is delayed for more than 250ms or so.

**Comment by sebastinez** [comment]
> The sample transition looks great! Simple & smooth. My only thought was: without knowing much about the internals of this app, are all the route chunks loaded ahead of navigation already or is the fade-in of the new route deferred until some chunk was fetched? If the latter, I'd be thinking about fading in a spinner _only if_ the new route loading is delayed for more than 250ms or so.

Thanks @efstajas for your input, yeah that's something we are working on and have merged with https://github.com/radicle-dev/radicle-interface/pull/358, not visible in my sample video, will post an update

**Comment by sebastinez** [comment]
Will close this issue for now since it's not a priority
