### ISSUE TITLE
Bad 404

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#367]
Currently, no matter what page you land on, if it doesn't exist you get this:
<img width="293" alt="image" src="https://user-images.githubusercontent.com/40774/188609196-08aa8172-6832-4f59-a052-d89a2a59aabf.png">

Eg. `/foo/bar/baz`

We should maybe say:
```
404

There's nothing here.
```

**Comment by sebastinez** [comment]
Thought about this issue and wanted to give my opinion.

We have a few cases here,

### `/foo`
We parse as a profile, where we catch a missing profile with `Sorry, the requested address or domain was not found.`

### `/foo/bar`
This is interpreted as a profile pointing to a project, here we could:
1.  If the profile `foo` doesn't exist fallback to `Sorry, the requested address or domain was not found.`
2. If the project is not valid we should go with `This project was not found`

### `/foo/bar/baz`
Here I would still say.
1. If `foo` is not a valid profile name we should go with `Sorry, the requested address or domain was not found.` 
4. If the project is not valid we should show `This project was not found`
5. And if profile and project are valid we should go with `404 Theres nothing here`

**Comment by cloudhead** [comment]
Hmmm, the thing is it will be very brittle if we do it like that. The only cases where we should be giving out specific 404 messages is when we know for sure, eg. `/seeds/xyz` where xyz doesn't exist, or `/seeds/foo/project123` where project123 doesn't exist.
