### ISSUE TITLE
Confusing UX in header search bar

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#368]
When I enter something in the header "search bar" and click `Register`, the app navigates to the `registrations` route, but the registration is not pre-filled with the text I entered in the header input.

<img width="1840" alt="Screenshot 2022-09-06 at 14 36 13" src="https://user-images.githubusercontent.com/158411/188636830-054d464c-47d4-4fd9-89dd-6aba29a5542e.png">

However, when I write something in the header "search bar" and then hit the <kbd>enter</kbd> key, the app navigates to the page of the ens name.

<img width="1840" alt="Screenshot 2022-09-06 at 14 36 06" src="https://user-images.githubusercontent.com/158411/188637434-c9d67166-0ad4-46bf-8b00-1ccc0425b431.png">

I only understood that the "Register" button doesn't belong to the input after I discovered that the input is submitted via the <kbd>enter</kbd> key. Therefore I think we should somehow visually disconnect the search input from the `Register` button, because they're two separate things.

**Comment by brandonhaslegs** [comment]
Hm, yeah. I mean the prefilled text does say "Search a name or address" _but still_ I think we could:

1. move "Register" over to the right side of the header
or
2. Move "Register" under a dropdown after you've connected a wallet. That dropdown could hold future stuff like a settings page, a "disconnect wallet" button, a "view profile" button … etc

I'd be for option 2.

**Comment by cloudhead** [comment]
Oh interesting, I think we can start with (1) since it's very quick to do.
