### ISSUE TITLE
Make relative links work in markdown

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#374]
Make sure relative links work within rendered markdown and fix formatting.

Here's the [reference markdown file](https://app.radicle.xyz/seeds/maple.radicle.garden/rad:git:hnrkfgsbjgkqggsfoty5noz5bxr6eqqsbzsmy/tree/142d87f82ff5ca3bf0a5aa4ce25979298c67c1d1/markdown-cheatsheet.md#lists).

How it could be:
<img width="298" alt="Screenshot 2022-09-08 at 11 51 42" src="https://user-images.githubusercontent.com/158411/189092340-4f1c039f-ef76-4253-80c6-fda3e12864b8.png">

vs how it is now:

<img width="968" alt="Screenshot 2022-09-08 at 11 51 15" src="https://user-images.githubusercontent.com/158411/189092395-7e0e67e1-a4d7-4fdb-9d97-f3838ecb5f07.png">

**Comment by cloudhead** [comment]
Does this use special syntax? I'd start by just auto-anchoring all headers I think.

**Comment by rudolfs** [comment]
Good point. Looking at the reference md file, it looks like it's actually just a manual list and some anchor tags:

```
##### Table of Contents
[Headers](#headers)
[Emphasis](#emphasis)
[Lists](#lists)

...
<a name="headers"/>
...
<a name="emphasis"/>
...
<a name="lists"/>
```

**Comment by rudolfs** [comment]
We had to revert #382 because it introduced hard wrapping in our RIPs: https://github.com/radicle-dev/radicle-interface/commit/7a393066224d434bd6e26960cd57af152fc3cfa3.

Should find a better solution for this.

**Comment by rudolfs** [comment]
Turns out that my editor removed significant whitespace from this document before I committed it.

https://app.radicle.xyz/seeds/maple.radicle.garden/markdown/tree/main/markdown-cheatsheet.md
Replaced it with the original whitespace in tact and it works now:

<img width="1840" alt="Screenshot 2022-12-12 at 16 25 11" src="https://user-images.githubusercontent.com/158411/207084269-87625376-f15f-4297-8336-788ad39b83d0.png">
