### ISSUE TITLE
Manage anchor proposals

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#39]
If an anchor has been proposed, but is missing signatures, it should be shown in the org view.

* On `/orgs/:address`, there should be a section that shows proposed anchors
* Only org members should see the proposed anchors
* The page should allow members to add their signature/confirmation to the anchor proposal
* The number of required signatures should be shown
* The members who signed the proposal should be shown

### Notes

* `SafeServiceClient.getPendingTransactions` to get proposals
* `SafeServiceClient.decodeData` to find out if the tx is an anchor proposal
* `SafeServiceClient.confirmTransaction` to sign a proposal
* To execute the proposal, we can use the SafeCoreSDK

**Comment by Khay-EMMA** [comment]
@cloudhead I want to take this issue

**Comment by sebastinez** [comment]
@cloudhead I'll work a design proposal for this issue and then implement a first version of this using the current OrgV1 contract.
If we move later to a L2 with anchors we can update the interface to manage them on the defined L2 solution.

**Comment by cloudhead** [comment]
Cool. Some of this is already implemented, some isn't FYI :)
