### ISSUE TITLE
Gracefully handle API quota exhaustion

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#398]
At the moment we just show a bunch of errors in the console and the `Connect` button is blank. We should at least fix the button.

<img width="1840" alt="Screenshot 2022-09-21 at 12 04 27" src="https://user-images.githubusercontent.com/158411/191476910-2e87eff7-8fb0-42c6-bff3-adbb0c3c4901.png">

**Comment by cloudhead** [comment]
Yeah, I think we don't actually need the results coming from the graph right now, we should just fallback gracefully.
