### ISSUE TITLE
show some kind of notification or feedback if there are no search results

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#412]
Ok here a first idea, on what we could do as feedback if no results are found.
I think it's very clear on the message, and transmits the information better than any text.

https://user-images.githubusercontent.com/7912302/192056656-3100d4d8-9687-4641-96d8-3f054e7af57a.mov

**Comment by cloudhead** [comment]
Love it!

**Comment by rudolfs** [comment]
😍 really nice!

**Comment by sebastinez** [comment]
Closed by #421 and #418
