### ISSUE TITLE
Markdown support for rendering math

### ISSUE THREAD

**Issue by heytdep** [radicle-dev/radicle-interface#413]
Github supports an incredibly powerful and useful syntax for writing math, i.e I can write $a^2 + b^2 = c^2$ with `$a^2 + b^2 = c^2$`.

Since `rad-cli` does an incredible job in making the transition from github to radicle easy, I think it would be great to add support for this kind of rendering also in the radicle interface which currently doesn't support the feature:
(from https://app.radicle.xyz/seeds/pine.radicle.garden/rad:git:hnrkp5jgfxwxrffjsp148fyzdc457pa9ja38y/tree)
![tmyxer__A_native_and_open-source_coin_mixer_for_the_Stellar_network_](https://user-images.githubusercontent.com/70587974/192151477-c0ef5614-502a-4b6c-bd21-b36b755b8608.png)

**Comment by sebastinez** [comment]
Hey @heytdep thank you very much for your issue! 👍 we'll look into this, it surely is something we want to support!
