### ISSUE TITLE
Small markdown padding bug in code block

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#428]
<img width="881" alt="image" src="https://user-images.githubusercontent.com/40774/193229196-3f07ffda-6848-4b13-a894-f7c65cc901f6.png">

**Comment by sebastinez** [comment]
Hmm tried to reproduce this issue, but seemed like everything was padded nicely.
@cloudhead Do you have maybe a repo somewhere, where I could look at it?

**Comment by cloudhead** [comment]
Sorry forgot to add the URL: https://app.radicle.xyz/seeds/clients.radicle.xyz/rad:git:hnrkjybkt1knwwq64ig7cxkt19xtcf6bpeugy/tree/e32617d4d289204446d5225f81dd91098cdd6cd7
