### ISSUE TITLE
Support custom seed node ports

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#440]
Some users, eg. TheGraph use port `443` to serve their HTTP APIs. This is incompatible with the app at the moment, which defaults to `8777`. To accomodate these users, it would be nice if we could simply support port numbers in the path, like so:

`app.radicle.xyz/seeds/maple.radicle.garden:443/`

We'd still default to 8777, but at least it becomes possible to view seeds on different ports. This port configuration would have to be passed down to the project pages.

**Comment by sebastinez** [comment]
Interesting, will make sure to take this into account in #450  👍

**Comment by rudolfs** [comment]
For example: https://app.radicle.xyz/seeds/api.radicle.thegraph.com doesn't load, but the api itself works on port 443: https://api.radicle.thegraph.com.

**Comment by sebastinez** [comment]
Closed by d885b4076d0d0dbe3303b1e974c7d1e5079e80b8
