### ISSUE TITLE
Small markdown design issue

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#459]
Looks like the line height on ordered lists is slightly smaller than the normal line height. Unordered lists also seem off.

<img width="786" alt="image" src="https://user-images.githubusercontent.com/40774/196734214-409ba824-eb7d-47bf-9bc0-c2def4e2cd85.png">
<img width="859" alt="image" src="https://user-images.githubusercontent.com/40774/196734712-7696768a-781e-46da-9ea4-b6db86d44393.png">

**Comment by sebastinez** [comment]
Ok found the issue.

While we define the `line-height` of a paragraph as `1.625` at https://github.com/radicle-dev/radicle-interface/blob/f8ddbbf5daf5195c556218d591a1a5a64769175c/src/Markdown.svelte#L131

For any other non `p` element we use `line-height: 1.5` as defined in `typography.css` https://github.com/radicle-dev/radicle-interface/blob/f8ddbbf5daf5195c556218d591a1a5a64769175c/public/typography.css#L47

So we should probably remove the `1.625` line-height introduced with https://github.com/radicle-dev/radicle-interface/commit/0a559d577b06b327bf7f11e5d23d07389705009d
