### ISSUE TITLE
Move syntax highlighting to frontend

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#497]
Heartwood won't support syntax highlighting in the backend.
It also just makes more sense to have it in the frontend.

**Comment by cloudhead** [comment]
GitHub uses tree-sitter: https://github.com/tree-sitter/tree-sitter

Not sure if they run it via wasm or do it differently though.

**Comment by cloudhead** [comment]
GitLab seems to use Highlight.js, which is also promising (though older technology): https://github.com/highlightjs/highlight.js/
