### ISSUE TITLE
Store session state to avoid reconnection after page refresh

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#5]
Hi @cloudhead,

I noticed that on doing a page refresh the page looses the connection to the web3 provider because of a fresh state and one needs to connect again to Metamask.

If one would like to keep the session open, the session could be stored in `LocalStorage` and on a new visit or page refresh, could be checked if there is already something stored.
Or eventually to avoid storing app state in `LocalStorage` one could store a preference to keep the session open and this could execute Metamask to request the currently available accounts, without needing the interaction of the user to reconnect.

Please let me know what you think, would provide a PR for it.

Cheers

**Comment by cloudhead** [comment]
Hey, that sounds like a good idea. I'm not sure which of the two options is best, but whatever is simplest and less likely to break. Keep in mind also that eventually we'd like to abstract the provider away so it might connect via WalletConnect or some other method.
