### ISSUE TITLE
A few extra things for the settings drop down

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#502]
- [x] Capitalize "system" in settings dropdown
- [x] Remove line between "Jetbrains" and "system" (lines should be between explicit settings groups, not between subgroups, [see design](https://www.figma.com/file/owmgsbs6lnUt8R1bixstCA/%F0%9F%8C%B1-Radicle?node-id=13740%3A226226&t=OHLQmBAzxRtrtqXV-4))
- [x] Make Jetbrains the default code font

<img width="287" alt="image" src="https://user-images.githubusercontent.com/4406983/203554515-6af574c2-1fb2-4a3d-8e61-b67916d01357.png">

**Comment by sebastinez** [comment]
Hey @brandonhaslegs thanks for the feedback, yeah the line did sneak back in.
And we can capitalize "system"

not sure on the default code font, @cloudhead wdyt?

**Comment by cloudhead** [comment]
Yeah I think lots of people have courier as their default font or some other shitty font. So it makes sense to default to JetBrains.
