### ISSUE TITLE
Explore introducing higher contrast to the UI

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#507]
I think this would improve the contrast of the UI a lot. Right now it feels a bit washed out, but I think this would do a lot. Need to do a fuller design exploration on it though. And not sure how it would translate to dark mode.

<img width="1236" alt="image" src="https://user-images.githubusercontent.com/4406983/203625893-a3540b14-0800-40eb-8bf8-feae01bdf42f.png">

**Comment by cloudhead** [comment]
This looks much better :+1:
