### ISSUE TITLE
Fix border radius on bottom right and left corners of these blocks

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#508]
Looks like an inner element needs to be rounded to make them not poke out of their containers.

This example is on the bottom of the README element here https://app.radicle.xyz/seeds/clients.radicle.xyz/rad:git:hnrkjajuucc6zp5eknt3s9xykqsrus44cjimy/tree

<img width="917" alt="image" src="https://user-images.githubusercontent.com/4406983/203626114-f21d202c-ec00-47f6-984d-635ec078b67a.png">

**Comment by sebastinez** [comment]
Closed by #509
