### ISSUE TITLE
Banner on Org first creation

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#51]
... Which tells you how to set the name.

**Comment by sebastinez** [comment]
Hey @cloudhead, do you have any news on this? I could elaborate some mock-ups so we can progress with this and use it for the org wizard

**Comment by cloudhead** [comment]
I've deprioritized this for now, as it's not as important as adding new functionality yet. If you want to take a stab at it though, feel free and assign yourself!

We basically want a Banner component that can be closed and has some text showing in it. Once it's closed, it doesn't show up, for the given org. But shows up if you create another org later.

I think this could be achieved by using the svelte `setContext`? If not, then perhaps LocalStorage. I don't want anything to be added to the URL, as that URL will likely be shared as-is.

**Comment by cloudhead** [comment]
If we want this to be used in a bunch of places, perhaps having programatic access, eg. `banner.set(<url>, <markdown>)` could be nice.

Otherwise we can simply have that logic inside the view that has the banner, and have a helper, like, `{#if banner.isSet(window.location)} <Banner>blah blah</Banner>{/if}`

**Comment by cloudhead** [comment]
Closing as orgsV1 are being phased out.
