### ISSUE TITLE
Track missing postinstall script execution on Netlify

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#511]
This issue is to track the missing postinstall execution, that we see in our Netlify builds.

While `npm install` and the subsequent `npm run build` are being triggered we don't see the `postinstall` scripts running, which means we don't get the twemoji and katex assets in our builds.
While a manual cache clearing removes the issue, this should be something we can automate.

Here are some PRs and issues that are seeing the same issue with Netlify on the `build-image` repo.
https://github.com/netlify/build-image/issues/113
https://github.com/netlify/build-image/issues/523

**Comment by rudolfs** [comment]
This seems to have been resolved. Haven't seen any issues with the twemojis recently.
