### ISSUE TITLE
Don't run CI checks twice on every push

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#517]
There has to be a better way. Maybe some github action?

<img width="833" alt="Screenshot 2022-12-01 at 16 01 36" src="https://user-images.githubusercontent.com/158411/205086496-8897e9c5-ee6b-43af-a96e-541708f028b5.png">

**Comment by sebastinez** [comment]
I think we could remove `pull_request` as a GitHub Action event.
`push` seems like already enough as it is
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
> Runs your workflow when you push a commit or tag.

`pull_request` seems like not enough, e.g. if something is pushed directly to master the CI wouldn't get triggered.

**Comment by rudolfs** [comment]
Don't think there's an easy way around this. Also not super important.
