### ISSUE TITLE
Upgrading transitive dependencies breaks production build

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#520]
This prevents us from upgrading transitive dependencies.

```
rm -rf node_modules
rm package-lock.json
npm cache clean --force
npm install
```

Then build and open the production app: http://127.0.0.1:4173
```
npm run build && npm run serve
```

```
auth.92021912.js:625 Uncaught ReferenceError: Buffer is not defined
    at new la (auth.92021912.js:625:63)
    at Nr.generateApi (auth.92021912.js:765:41)
    at auth.92021912.js:765:284
```

<img width="1840" alt="Screenshot 2022-12-01 at 16 32 10" src="https://user-images.githubusercontent.com/158411/205093629-91a17d7f-2556-4c53-bc78-9b571cdec3dd.png">

**Comment by sebastinez** [comment]
Okay this seems an issue with `siwe` relying on a package called apg-js which requires the native node Buffer package..
https://github.com/spruceid/siwe/issues/136

**Comment by rudolfs** [comment]
Fixed via https://github.com/radicle-dev/radicle-interface/pull/534.
