### ISSUE TITLE
Cache Playwright binaries on CI

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#521]
Downloading them each time is the second longest task on CI for e2e tests.
Here are some hints on how to do it: https://github.com/microsoft/playwright/issues/7249.

<img width="661" alt="Screenshot 2022-12-01 at 16 48 39" src="https://user-images.githubusercontent.com/158411/205097970-d91d3fae-c5bc-4e8c-8a14-bb9676e9bbc8.png">
<img width="681" alt="Screenshot 2022-12-01 at 16 48 44" src="https://user-images.githubusercontent.com/158411/205097987-bb345537-fc34-4e8d-8088-ec14445ae035.png">

**Comment by sebastinez** [comment]
Hmm yeah that seems like something that would be nice.
I even see currently that there are issues with installing them.. Maybe by doing it so often we generate some issue 🤔 
https://github.com/radicle-dev/radicle-interface/actions/runs/3594648973/jobs/6053173359
