### ISSUE TITLE
Modal on modal

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#524]
Feels like an anti-pattern. What's the correct way to solve this @brandonhaslegs?

<img width="1840" alt="Screenshot 2022-12-02 at 09 57 25" src="https://user-images.githubusercontent.com/158411/205255162-97cc1ba7-e8ec-453e-936e-c2b2b175e2a7.png">

**Comment by brandonhaslegs** [comment]
I think an anti pattern is something evil. This is just two modals overlapping right? I’d just hide the first modal while the second one is open.
