### ISSUE TITLE
Bug - "Back" button on final vesting modal does not work

### ISSUE THREAD

**Issue by bordumb** [radicle-dev/radicle-interface#525]
## Issue 

The "Back" button on the final vesting modal within the "Withdraw" flow (see below) does not work

![image](https://user-images.githubusercontent.com/3743841/205705506-5d4b3b7b-f39a-46ac-a086-b1c693ab3810.png)

## Expected Result

Close the modal and return to the original Contract's top page.

I would expect clicking the "Back" button to return to that page.
In code, I'd expect the "Back" button to hyper link to this:
```
https://app.radicle.xyz/vesting/{CONTRACT_ID}
```

## Actual Result

The button does not react to any clicks 

I'm on latest version of Chrome on latest MacOS

**Comment by sebastinez** [comment]
#552 closes this issue
