### ISSUE TITLE
Feature Request - Make vesting contracts more discoverable 

### ISSUE THREAD

**Issue by bordumb** [radicle-dev/radicle-interface#526]
## Overview

Below is an existing vesting contract:

https://app.radicle.xyz/vesting/0xed99ca7e08f89eA2503fF3b59C5B35980FdDe3E3

That is all well and good if we happen to know that the URL is:
```
https://app.radicle.xyz/vesting/{contract_address}
```

## Issue 

If I have a contract ID, but don't know the URL `https://app.radicle.xyz/vesting/{contract_address}`:
I would likely use the Search function at the top left of the site:

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/3743841/205707459-eee57b07-770e-4a51-bba1-cfa61239a37b.png">

This gives me this URL:
https://app.radicle.xyz/0xed99ca7e08f89ea2503ff3b59c5b35980fdde3e3

Let's call this an "Address Profile Page"

This "Address Profile Page" happens to be for a contract.
But it does not (a) have real contract info or (b) link to the vesting page.

## Proposal

It would be good if we had some sort of circular logic that more cohesively links this info to make the vesting information more discoverable.

For example, users' wallets do a pretty nice job of this:

If we go to this URL:
https://app.radicle.xyz/0x641edb587867a703e132a4210d63e93c52aa97ff

It offers the following info:
* Seed
* Address
* Profile

It would be nice if when entering a contract address to the URL, like https://app.radicle.xyz/0xed99ca7e08f89ea2503ff3b59c5b35980fdde3e3, it would provide:
* Contract (Radicle Vesting, Etherscan)

Whereby the pseudo code for displaying Contract (Radicle Vesting, Etherscan) might be like:
```
contract_address = '0xed99ca7e08f89ea2503ff3b59c5b35980fdde3e3'

radicle_vesting_url = f'https://app.radicle.xyz/vesting/{contract_address}'
etherscan_contract_url = f'https://etherscan.io/address/{contract_address}#code

markdown = f'Contract ([Radicle Vesting](radicle_vesting_url), [Etherscan](etherscan_contract_url)'
```

**Comment by sebastinez** [comment]
I like this very much, we could even remove the whole `vesting/` route or redirect it to a "Address Profile Page" where we detect if it's a vesting contract and in that case display the whole vesting information.

**Comment by sebastinez** [comment]
The withdraw feature can be shown as a small button on the right side of the withdrawable vesting amount, which once clicked we show a modal which guides the user through the process and then goes back to the "Address Profile Page"

**Comment by bordumb** [comment]
> I like this very much, we could even remove the whole `vesting/` route or redirect it to a "Address Profile Page" where we detect if it's a vesting contract and in that case display the whole vesting information.

I REALLY like this idea.

Like there could be a standard URL param that is simple/intuitive for 100% of cases:
```
https://app.radicle.xyz/{contract_address}
```

And a decision tree sort of logic, whereby it displays different profile "types" depending on what the address is. Pseudo code like:
```python
registered_wallet_address = '0xRegisteredWalletAddress'
unregistered_wallet_address = '0xUnregisteredWalletAddress'
contract_address = '0xContractAddress'

wallet_address = '0xMyRegisteredWalletAddress'

base_url = f'https://app.radicle.xyz'

def is_registered_wallet_address(address: str) -> bool:
    """Boolean function that determines whether a given address is a wallet address that has a profile registered to ``x.radicle.eth``."""
    return True if 'Registered' in address else False

def is_unregistered_wallet_address(address: str) -> bool:
    """Boolean function that determines whether a given address is a wallet address that does not have a profile registered to ``x.radicle.eth``."""
    return True if 'Unregistered' in address else False

def is_contract_address(address: str) -> bool:
    """Boolean function that determines whether a given address is a wallet address that has a profile registered to ``x.radicle.eth``."""
    return True if 'Contract' in address else False

def display_front_end(address: str):
    print(f"URL: {base_url}/{address}")
    if is_registered_wallet_address(address=address):
        display_layout = f"""Registered Profile UI: ENS, {address}, name.radicle.eth"""
    if is_unregistered_wallet_address(address=address):
        display_layout = f"""Unregistered Profile UI: {address}"""
    if is_contract_address(address=address):
        display_layout = f"""Contract Profile UI: {address}, Contract Modal, etc."""
    print(display_layout)

display_front_end(address=registered_wallet_address)
# URL: https://app.radicle.xyz/0xRegisteredWalletAddress
# Registered Profile UI: ENS, 0xRegisteredWalletAddress, name.radicle.eth
display_front_end(address=unregistered_wallet_address)
# URL: https://app.radicle.xyz/0xUnregisteredWalletAddress
# Unregistered Profile UI: 0xUnregisteredWalletAddress
display_front_end(address=contract_address)
# URL: https://app.radicle.xyz/0xContractAddress
# Contract Profile UI: 0xContractAddress, Contract Modal, etc.
```

**Comment by bordumb** [comment]
@sebastinez 

I just realized GitHub actually this with User Profiles versus Org Profiles in a fairly analogous way.

For example, in either case, the URL is:
```
www.github.com/{profile_name}
```

Here is my individual profile:
https://github.com/bordumb

And here is an organizations profile:
https://github.com/radicle-dev
