### ISSUE TITLE
Bug - "Log In" button on seed profile page isn't working

### ISSUE THREAD

**Issue by bordumb** [radicle-dev/radicle-interface#528]
## Overview

If I visit this seed page:
https://app.radicle.xyz/seeds/clients.radicle.xyz

There is a "Log In" button that appears.

If I click "Log in" and go through the flow, nothing happens.

See screen recording:

https://user-images.githubusercontent.com/3743841/205753593-5f31fc97-bcdb-42bc-bdd6-9d7be9704aba.mov

**Comment by sebastinez** [comment]
Thanks @bordumb for creating the issue, it's an issue between http-api and the web client..
I think we'll wait for heartwood to be released and see how we will use SIWE or other login methods before tackling this again.

**Comment by sebastinez** [comment]
PR #534 removed the SIWE functionality for now, so I'll close this issue.
