### ISSUE TITLE
Side-by-side diff comparison

### ISSUE THREAD

**Issue by bordumb** [radicle-dev/radicle-interface#529]
## Current Behavior

Radicle currently does "unified" or top/bottom diff comparisons (sample below)

<img width="781" alt="image" src="https://user-images.githubusercontent.com/3743841/206011776-fc812eb7-9c07-403e-8c1b-f727eb55d6da.png">

## Proposal

A lot of Enterprise/private instances of GitHub default to "split" or side-by-side diff presentation.

And public GitHub has this drop-down to switch between modes, using "split" below:

<img width="1441" alt="image" src="https://user-images.githubusercontent.com/3743841/206011996-8a4becfd-93e8-442f-ad43-71381551255c.png">

## Priority 

The app already gets the job done, so this is low priority. 

I just think having side-by-side diff is easier to read/compare.
This is def a nice to have.

**Comment by rudolfs** [comment]
Moved over to Radicle

https://app.radicle.xyz/nodes/127.0.0.1:8080/rad:z4V1sjrXqjvFdnCUbxPFqd5p4DtH5/issues/2c6868fe18dc9a628704250f3884b547097aaa1c
