### ISSUE TITLE
Improve display and formatting of ethereum addresses

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#555]
This is a normal thing most dApps do. It’s just annoying to always see so many unnecessary super long addresses in an interface.

Typically the first 4 and last 4 are shown with a `…` in between.

**Comment by sebastinez** [comment]
I think there are surely improvements on where we show the full address vs. a truncated one.
Maybe we can track all the places here where truncated addresses would be better than the full address?

**Comment by brandonhaslegs** [comment]
Hard to find places where addresses even are in the app. But happy to point out where I think they could be shortened. For now though, I can’t find any!

**Comment by sebastinez** [comment]
I think one place that could benefit from shorter addresses is the profile page, when the main title isn't resolvable to a ENS address.
I think the big address can be shortened and the smaller one can show the entire address for verification purposes.

**Current** 
<img width="903" alt="Bildschirm­foto 2023-01-02 um 18 50 17" src="https://user-images.githubusercontent.com/7912302/210264872-dc02ebf2-01ea-44a2-9a2d-c34a5860c4fa.png">

**Proposed**
<img width="623" alt="Bildschirm­foto 2023-01-02 um 19 50 57" src="https://user-images.githubusercontent.com/7912302/210269468-81db583c-8183-455f-b448-666537a4afa0.png">

**Comment by sebastinez** [comment]
Will close this, since we don't show any ethereum addresses anymore
