### ISSUE TITLE
Notification component (toast) 🍞

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#556]
Would like to show some sort of notifications in the UI when things happen or when action is required. Would be great to have when building features. Still needs design but just starting this issue to track it.

**Comment by rudolfs** [comment]
Talked to @cloudhead about this. We won't be doing toasts unless we have some kind of transactions that require real time notifications. The reasoning being that we should be able to get by with rendering the errors within the view, just like Github.

**Comment by rudolfs** [comment]
Will close this for now until we need this type of functionality in the app.
