### ISSUE TITLE
Search field remains filled after navigating the app

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#569]
If you enter text into the search field, then navigate somewhere else in the web app, the search field remains filled.

I expect the search field to empty out when I navigate to another page.

![search content persistent](https://user-images.githubusercontent.com/4406983/210080799-4d10bc8c-35e8-4242-916d-69873ac43727.gif)

**Comment by rudolfs** [comment]
Why tho? It's a global element, it works independent on which page you interact with it.
On Github the search bar isn't cleared either.

https://user-images.githubusercontent.com/158411/210523992-e7530367-3978-4214-bc40-34edff6114c7.mov

**Comment by brandonhaslegs** [comment]
It’s not cleared if you stay on the same page on GitHub, but when you navigate away of course it's cleared. It’s just weird I’ve never seen anything like it.

**Comment by brandonhaslegs** [comment]
@efstajas what u think?

**Comment by efstajas** [comment]
Hmm, tbh i don't see a problem with it staying 🤷 feels like on github they don't explicitly clear it either – it just stays after an AJAX navigation, but clears as a side-effect of a full navigation. Having it clear isn't worse IMO. I'm indifferent. Doesn't feel weird to me either way.

**Comment by rudolfs** [comment]
Alright, let's clear it, since Sebastian already implemented it.
