### ISSUE TITLE
Add form validation to the registration view

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#58]
Currently it's possible to save bogus data in ENS, via `/registrations/:label`, eg. you can set a URL as the twitter handle. We should validate inputs on Save.

**Comment by sebastinez** [comment]
Hmm I was thinking about this issue and we could eventually add regex expressions in the initialization of the fields array @ https://github.com/radicle-dev/radicle-interface/blob/8a6c2938a63a3f924d0a3c1de3dc536c3300e525/src/base/registrations/View.svelte#L46

For example:
```diff
  fields = [
-   { name: "owner", placeholder: "", value: r.owner, resolve: true, editable: false },
+  { name: "owner", placeholder: "", value: r.owner, resolve: true, editable: false, validation: "[a-zA-Z0-9]+" },
-   { name: "url", label: "URL", placeholder: "https://acme.org", value: r.url,editable: true }
+  { name: "url", label: "URL", placeholder: "https://acme.org", value: r.url,editable: true, validation: "^(https:|http:|www\.)\S*" }
]
``` 

And then in the `onSave` function in https://github.com/radicle-dev/radicle-interface/blob/8a6c2938a63a3f924d0a3c1de3dc536c3300e525/src/base/registrations/View.svelte#L74 we could iterate over the values and validate the values with `f.value.match(f.validation)`

**Comment by cloudhead** [comment]
That's not a bad idea, though since there are only a few types of fields, what if we defined validation _types_ and had the validation logic inside Form?

Eg. `{ name: "url", validate: "url", ... }`, then in Form we'd check if `validate` is set. If it's undefined, we don't validate the field.

This would keep us from having regexes all over the place. We could have "url", "handle", "address" for now.

In terms of displaying errors we can highlight the field and show the value of the "validate" property like `Invalid input, expected ${validate}`.

**Comment by sebastinez** [comment]
@cloudhead 
> show the value of the "validate" property like Invalid input, expected ${validate}.

Do you mean replacing the typed value with the mentioned text or replacing the tooltip?
IMO I would replace the tooltip to not alter the information entered by the user.

**Comment by cloudhead** [comment]
Yeah the tooltip of course!

**Comment by sebastinez** [comment]
#68 closed this issue
