### ISSUE TITLE
Migrate to wallet connect v2

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#586]
v1 was sunsetted, everyone has to migrate by feb 28.

https://medium.com/walletconnect/walletconnect-v1-0-sunset-notice-and-migration-schedule-8af9d3720d2e

This might also be a good opportunity to look at our `session` and `wallet` modules and do a refactor.

**Comment by sebastinez** [comment]
Okay according to what we talked over Discord (https://discord.com/channels/841318878125490186/856904179820920833/1069181291284660286) we'll remove all eth functionality from the web app, so this PR is not needed anymore
