### ISSUE TITLE
Redesign interactivity of search bar

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#593]
It feels a bit dead when it's focused.

**Comment by cloudhead** [comment]
The fate of the search bar needs to be examined first in heartwood. Otherwise I'd say we could just have it grow to the right when hovered.

**Comment by rudolfs** [comment]
What about something like this?

https://user-images.githubusercontent.com/158411/216089326-9b2ed273-70e9-46e1-a7b4-c79ce873bddb.mov

**Comment by cloudhead** [comment]
That's exactly what I had in mind :+1:

**Comment by cloudhead** [comment]
I think it should search your local node actually, so we should provide some indication of that eventually.
