### ISSUE TITLE
Add "radicle" to header

### ISSUE THREAD

**Issue by brandonhaslegs** [radicle-dev/radicle-interface#594]
Here is the logo with the font

![radicle logo](https://user-images.githubusercontent.com/4406983/215426410-5aa85aae-abad-44f4-9181-ff99939c8961.svg)

**Comment by brandonhaslegs** [comment]
BTW Alexis mentioned he doesn't want to have the logo colors be the same as the token (and maybe the circle shouldn't be there) easy enough to remove from the SVG once it's implemented tho.

**Comment by brandonhaslegs** [comment]
> It's more the circle around it that I want to avoid 

Just a thought I had… but yeah anyway we can probably close this if we're agreeing to not put "radicle" up there.
<img width="435" alt="image" src="https://user-images.githubusercontent.com/4406983/215532601-ff293d4a-b9f9-4879-8ece-8fd6ab4b7a14.png">

**Comment by cloudhead** [comment]
The rounded square is interesting :thinking:
