### ISSUE TITLE
Implement Linter

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#6]
Hi @cloudhead,

Wanted to know if you thought about implementing some kind of linter like ESLint to enforce code standards and style?
If you agree I could propose some standard rules that apply to the current code and enforce it for future contributions.

Cheers

**Comment by cloudhead** [comment]
At the moment I'm not too keen on having more configuration and tooling to run, though I think it would be good to setup CI as a first step. I will look into the linting story to see how much churn it would create if we adopted it.

**Comment by sebastinez** [comment]
I agree with implementing too much CI, nevertheless I think some basic code formatting and a pre-commit hook would be great and contribute hugely to standardize the codebase.

I'll elaborate on a branch the usage of prettier adapting the current code style and we can work on that.

**Comment by sebastinez** [comment]
@cloudhead Defining a possible configuration file for the auto-formatter, there were some parts that weren't clear from the code base, eventually you could decide on those points.

- Use single quotes or double quotes.
- [Change when properties in objects are quoted.](https://prettier.io/docs/en/options.html#quote-props)
  - In my opinion the preserve option is the most adequate here

For the other options I think I found a sane configuration file to maintain CI to a minimum for now.
Here the options page https://prettier.io/docs/en/options.html
