### ISSUE TITLE
Provide a way for responsible security disclosure

### ISSUE THREAD

**Issue by slack-coder** [radicle-dev/radicle-interface#615]
Provide an easily discoverable way for responsibly disclosing security vulnerabilities.

One standard is [security.txt](https://securitytxt.org/).  Check out github's [security.txt](https://github.com/.well-known/security.txt).

**Comment by sebastinez** [comment]
Thanks @slack-coder for the issue, I'll list some things we need to create the `security.txt` and close this issue.

- [ ] A security mail, maybe something like `security@radicle.xyz`? Not sure who has the permission to create mails.
- [ ] An expiration date, I would propose to do a yearly review of the information.
- [ ] A pubkey which people should use to encrypt the disclosure, @cloudhead can you maybe provide one here?
- [ ] Security policy, I think I can write something up and post it on our discourse to get some feedback.

**Comment by sebastinez** [comment]
Migrated to Radicle

https://app.radicle.xyz/nodes/seed.radicle.xyz/rad:z4V1sjrXqjvFdnCUbxPFqd5p4DtH5/issues/553027371caa9935bdce881b630fa941d7707b13
