### ISSUE TITLE
Provide a deployment for pre heartwood stack

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#616]
I'm seeing increasingly parts of the web client that will be stripped down to only support heartwood once heartwood happens for the public. Eventually the web app won't handle pre heartwood seed nodes and identities, will forget what Radicle Ids are and how to handle project data, etc.

So I think we should provide some deployment of the web app with these functionalities  still working, maybe on a separate branch, where we don't strip away the pre heartwood features. And hosted under a different subdomain.
The goal nevertheless is that everyone migrates to heartwood, but there are already some people running the current CLI and running `radicle-client-services/http-api` seed nodes.
wdyt @cloudhead @rudolfs

**Comment by rudolfs** [comment]
I think the consensus is to leave everything as is until we migrate to Heartwood.
