### ISSUE TITLE
Make CLI tooling scriptable from within tests

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#653]
We need this to be able to test patches and issues.

For this we need:
  - to be able to download the `rad` binary (similar to how we do it with `radicle-httpd`)
  - set up the environment (ssh-agent, paths)
  - make the api for it parametrisable, so we can perform actions as different nodes

If we have this, we might also be able to get rid of the seed fixtures.

**Comment by cloudhead** [comment]
Small note: you don't need ssh-agent, you can use `RAD_PASSPHRASE` instead, for tests.

**Comment by sebastinez** [comment]
I'll take a stab at this
