### ISSUE TITLE
Handle WalletConnect network change

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#66]
Currently, the app doesn't respond to changes to the network, in a WalletConnect mobile app that is connected. And if the network doesn't match on connect, an error is thrown.

We should look into handling this differently, at least when Metamask is not present, or if there's a way to switch the Metamask network that's even better.

The issue that makes this not so simple is that with Metamask, you always have a wallet connected, and if the networks don't match, which one takes precedence?

**Comment by Khay-EMMA** [comment]
I think switching the network on metamask to the currently connected wallet connect network will work

**Comment by Khay-EMMA** [comment]
Also if the networks doesn't match and we choose walletConnect, the provider still uses the metamask network??

**Comment by cloudhead** [comment]
> I think switching the network on metamask to the currently connected wallet connect network will work

If this is possible, then maybe itt's a good idea, though it could be annoying for users who are using metamask on other websites too..

Can you see how uniswap or compound handle this?

**Comment by cloudhead** [comment]
> Also if the networks doesn't match and we choose walletConnect, the provider still uses the metamask network??

That's one of the problems yeah if Metamask stays on the wrong network.

**Comment by Khay-EMMA** [comment]
> > I think switching the network on metamask to the currently connected wallet connect network will work
> 
> If this is possible, then maybe itt's a good idea, though it could be annoying for users who are using metamask on other websites too..
> 
> Can you see how uniswap or compound handle this?

Let me see how they handle it first

**Comment by Khay-EMMA** [comment]
> > I think switching the network on metamask to the currently connected wallet connect network will work
> 
> If this is possible, then maybe itt's a good idea, though it could be annoying for users who are using metamask on other websites too..
> 
> Can you see how uniswap or compound handle this?

Uniswap uses web3react for this integration, so I'm looking at how web3react handles walletConnect network change

**Comment by Khay-EMMA** [comment]
so basically when a user changes the network from walletconnect, I can trigger this method to change the network on metmask https://docs.metamask.io/guide/rpc-api.html#usage-with-wallet-switchethereumchain

**Comment by Khay-EMMA** [comment]
This is one approach tho

**Comment by cloudhead** [comment]
Ok, I mean so far that's the best approach I can think of. Do you have other ideas?

**Comment by sebastinez** [comment]
@cloudhead is this still being worked on? Can I take a stab at it?

**Comment by cloudhead** [comment]
Yeah go ahead!
