### ISSUE TITLE
Flickering in project page

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#668]
I'm noticing flickering on the project page when switching for eg. between issues and commits, or between closed and open patches. Often, more than the sub-view refreshes, even though nothing changes there. I think there's two steps to fixing this:

1. Figure out why things that aren't changing get re-rendered
2. Have the data required data pre-loaded before switching views so that we don't see a blank state.

**Comment by rudolfs** [comment]
We moved all of the data loading that would cause a page to flicker to the router now.
