### ISSUE TITLE
Add a way to obtain a patch or diff plaintext views

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#684]
I think this would be really nice to have to apply a patch easily.

Not yet sure if we want to provide this as part of the web app or send the user to a httpd route that provides these plaintext files

**Comment by rudolfs** [comment]
It could be just a simple copy-to-clipboard button. Then the user can just do `(pbpaste; echo) | git apply` in the repository.

**Comment by rudolfs** [comment]
Just to clarify, what is the actual use case here? Because the `rad` CLI tooling allows checking out a patch in the working copy, correct?

**Comment by sebastinez** [comment]
Yeah the CLI allows checking out and looking at the patch changes.
The use case would be similar to what GH does with the `.diff` and `.patch` routes
https://github.com/radicle-dev/radicle-interface/pull/764.patch

But we can also close it for now, since it's pretty low priority.

**Comment by sebastinez** [comment]
Ok will close this in favor of issue [5e89c33](https://app.radicle.xyz/nodes/seed.radicle.xyz/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5/issues/5e89c33cdd41e83c1a5db3a8ec97616faaae2204) on the heartwood repo
