### ISSUE TITLE
Improve documentation on requisites for connecting to a local node, and or error message in CLI

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#685]
We should improve the `Connect` button explainer on how to connect to a local node.
Currently we only show
```
To connect to your local Radicle node, run this command in your terminal: rad web
```

So I have a few ideas how to improve thisa:
- Adding more text to the `Connect` button explaining the requirement of having `radicle-httpd`
- When trying to run `rad web` without having `radicle-httpd` showing a better output than
`✗ Web failed: http://0.0.0.0:8080/api/v1/sessions: Connection Failed: Connect error: Connection refused (os error 111)`
maybe something like `Not able to connect to your local `radicle-httpd` instance, please make sure you install it from <url> and run it with radicle-httpd`
  - Also we could maybe proactively download the binary if not available and execute it?

**Comment by sebastinez** [comment]
Nice yeah that seems nice, maybe we can also add a tooltip when hovering over the node status on what it means and how to start the node and the httpd

**Comment by rudolfs** [comment]
Can we close this now that https://github.com/radicle-dev/radicle-interface/pull/744 is merged?

**Comment by sebastinez** [comment]
Yes can be closed.
