### ISSUE TITLE
Patch comments wrap within words

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#687]
See https://app.radicle.xyz/seeds/seed.radicle.xyz/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5/patches/211384c3fec8df919077fad2a73378063dce31e6?tab=activity

Notice that the wrapping is breaking individual words instead of keeping the words intact.

**Comment by sebastinez** [comment]
Thanks @cloudhead this probably showed up now after removing the soft breaks turning into line breaks
