### ISSUE TITLE
Testnet Faucet

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#69]
I open this issue to track and talk about a possible RAD Faucet on Rinkeby.

- [x] Show faucet in `radicle-interface` app when connected to Rinkeby Testnet

The contract part can be found in https://github.com/radicle-dev/radicle-faucet

**Comment by cloudhead** [comment]
Yeah perhaps we should rate-limit based on ENS names. Eg. each ENS name can only withdraw at most X per day.

**Comment by sebastinez** [comment]
> Yeah perhaps we should rate-limit based on ENS names. Eg. each ENS name can only withdraw at most X per day.

I concur, this would allow use to set a rate-limit without relying on social media, or other potentially centralized services.

**Comment by sebastinez** [comment]
This has been implemented with #104.
