### ISSUE TITLE
Patch numbers don't update

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#691]
I thought I opened an issue about this, but it seems like not:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/40774/232443173-0767d64e-da37-4d4f-9d22-0d702b909731.png">

This happens when for eg. a patch changes from open to merged, which works correctly, except the numbers don't change without a full refresh.

**Comment by cloudhead** [comment]
Yeah I updated from the CLI and then clicked around.

**Comment by cloudhead** [comment]
However the problem is not just with the patch state. If you add a new patch, the number also won't update even if it shows both patches.

**Comment by rudolfs** [comment]
I guess the proper way to address this would be to stream events to the front-end when there are changes to the storage. Just like we did in Upstream. And then in the view listen to these updates and load the data accordingly.

**Comment by cloudhead** [comment]
Hmm can't we just update the counters when we load new data from the backend?

**Comment by sebastinez** [comment]
Yeah that's what we do when changing state for issues. The probable cause for this is that the state counts come through the project endpoint which we load once when the project is fetched, so we need to probably refetch the project endpoint on every view change.

**Comment by cloudhead** [comment]
One related issue to this I wanted to mention is that we get the `[More]` button showing up even though there aren't more patches, and clicking it doesn't do anything.

**Comment by rudolfs** [comment]
> One related issue to this I wanted to mention is that we get the [More] button showing up even though there aren't more patches, and clicking it doesn't do anything.

Could you provide a link to where this happens?

**Comment by cloudhead** [comment]
https://app.radicle.xyz/seeds/seed.radicle.xyz/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5/patches

It only happens if a patch was merged or something for eg., while your window is open, I think.

**Comment by cloudhead** [comment]
<img width="1538" alt="image" src="https://github.com/radicle-dev/radicle-interface/assets/40774/e4f20a08-24f9-47ae-b227-b478fd239591">

7 open, but actually there's only 6 open, because one was merged. The [More] button is still there and if I click it, it turns to a loading indicator and then comes back.
