### ISSUE TITLE
Allow an easy way to access to the registration form

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#70]
Currently there is no easy way to end up in the registration form to edit ones information.
When searching for a ENS Name it resolves to the user page and when going through the registration process, the app informs only that the name is no longer available.

I have two  ideas how to solve this UX issue:
- When informing that the name is no longer available, check for the current user, and if corresponding, show a link to the registration form.
- In the Query resolve an explicit query to <ENS Label>.<ENS Subdomain> to the registration form.

**Comment by cloudhead** [comment]
Hmm, so for orgs you can access it via the org profile, by clicking on the name.
I think we should just add the same link in the user profile?

**Comment by sebastinez** [comment]
Yeah I guess that's also a solution. It seems not that straightforward, eventually we can add a `title` property to the ENS domain of the user?

**Comment by cloudhead** [comment]
Yeah I mean it's ok for now but we could also have a registration search I guess.

What would you have in the title property of the ENS domain?

**Comment by cloudhead** [comment]
Yeah I think that's a good idea.
