### ISSUE TITLE
Show reviews in patch sidebar

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#700]
Would be nice to show who accepted/rejected or commented on a patch in the sidebar, above "Tags".

Basically the same way github has a "Reviewers" section.

**Comment by cloudhead** [comment]
It would also be nice to see the number of comments if there are more than 0!

**Comment by sebastinez** [comment]
So I built this, to address the display of the Reviewers similar to GitHub.
<img width="1130" alt="Bildschirmfoto 2023-06-23 um 11 01 42" src="https://github.com/radicle-dev/radicle-interface/assets/7912302/9d5961d4-9140-44f3-900a-c27dd633645f">

But the following issue came up:
- Do we want to show only reviews for the latest revision? Or also reviews for previous revisions? (Maybe they can be shown greyed out)
wdyt @cloudhead ?

**Comment by sebastinez** [comment]
> It would also be nice to see the number of comments if there are more than 0!

I assume you mean to display them in the patches listing? Similar to what we do with issues?

**Comment by cloudhead** [comment]
Yes to all comments.
As for the reviews, I think the issue with greying out is that it might get really busy, eg. if you rejected 5 revisions, your review will show up 5 times?

One alternative would be to show the latest review per reviewer.. But maybe to simplify for now we can just show reviews for the latest revision. We will want however to show the reviewer even if he hasn't reviewed this revision, but reviewed a previous revision. That way you know he's supposed to "update" his review. There is also a list of assigned reviewers per patch which we can show there as not having reviewed yet.

**Comment by sebastinez** [comment]
Yes what I meant is always show the latest review per reviewer.

> There is also a list of assigned reviewers per patch which we can show there as not having reviewed yet.

Good point, will add a state to show a still pending review.
How do these reviewers get assigned to a patch? With `rad assign`?
