### ISSUE TITLE
Browsing files shows `Empty file` message for a split second

### ISSUE THREAD

**Issue by xphoniex** [radicle-dev/radicle-interface#709]
This obviously lingers more if the connection is unstable/slower, ideally it should show "loading" first and then "empty file".

![empty-file](https://user-images.githubusercontent.com/14107758/234316078-9da71362-3da3-4280-8ec9-4e47fc3123db.png)

**Comment by cloudhead** [comment]
I still see this even though that pr is merged.

**Comment by rudolfs** [comment]
This still happens on page reload. See: https://app.radicle.xyz/seeds/seed.radicle.xyz/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5/tree/master/radicle-httpd/src/api/v1/projects.rs
