### ISSUE TITLE
App not loading if more than one wallet enabled

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#71]
> Okay, interesting edge-case. If you have 2 wallets enabled by mistake (e.g brave's native + metamask) there is an error from metamask that will block the website from even loading
> - Odyslam on #general discord channel

I was able to replicate it, will check where this error originates and instead of keep loading, show an error.

**Comment by sebastinez** [comment]
Hmm it seems that Svelte has some issues with bubbling up code, see https://github.com/sveltejs/svelte/issues/5129
Either way the issue comes from the Metamask/Brave side, it's not something that we trigger.. Or could bubble up..
Here another issue on Metamask that directs the blame to Brave. https://github.com/MetaMask/metamask-extension/issues/8012
Eventually Metamask or Brave could emit a Error Event we could listen to, to throw a specific error that could be shown to the end user, but this would have to be a PR on the corresponding repo.
In the meantime we could eventually create some kind of timeout that would trigger if no connection would establish after a few seconds.

**Comment by sebastinez** [comment]
Regarding the timeout trigger we could implement something like this:
```js
if (metamask) {
    const timer = setTimeout(() => {
      throw new Error("Not able to connect to Metamask");
    }, 4000);
    // If Metamask is detected, we use the network configured there.
    network = await metamask.ready;
    clearTimeout(timer);
  }
```

**Comment by sebastinez** [comment]
This issue is tightly coupled to the following issue I'm trying to resolve on ethers.js so if I get progress there I'll come back here.
https://github.com/ethers-io/ethers.js/issues/2055

**Comment by sebastinez** [comment]
1fb59fa closes this issue
@OdysLam sorry for the delay, please let me know if it is fixed for you.

**Comment by OdysLam** [comment]
Hey, 

Thanks! I worked around this a long time ago, by simply not having 2 wallets enabled. Let me test this once I am on my computer. 

Thanks for circling back to me!
