### ISSUE TITLE
Hover effect on patch title

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#718]
Could we underline instead of changing color, when hovering the patch/issue titles? Looks a bit weird right now.

**Comment by rudolfs** [comment]
Sure.

**Comment by rudolfs** [comment]
Is this what you had in mind @cloudhead?

<img width="757" alt="Screenshot 2023-04-28 at 11 54 42" src="https://user-images.githubusercontent.com/158411/235116849-95537381-4ac8-4201-9cc1-91eedbea3f68.png">
