### ISSUE TITLE
Indication that we're viewing an issue or patch

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#726]
Let's say you land here:

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/40774/235601377-836746a5-f28d-4349-a0c7-f3adce528139.png">

There's no clear indication that you're looking at an issue. The issues "tab" is not highlighted, and there's no other indication, except for the tiny text "opened this issue".

I think we should highlight the issue (or patch) tab, and maybe introduce a little icon like on github, next to the `open` indicator.

If we look at gitlab, here's a merge request:
<img width="563" alt="image" src="https://user-images.githubusercontent.com/40774/235602084-85e1e25b-08f1-4e61-91dc-5196d424f885.png">

And here's an issue:
<img width="764" alt="image" src="https://user-images.githubusercontent.com/40774/235602153-e0c69985-b666-41aa-be55-53a8b8c94bfa.png">

TBH I'm not sure why they use a different layout. But there's a few visible ways to distinguish them.

**Comment by rudolfs** [comment]
> There's no clear indication that you're looking at an issue. The issues "tab" is not highlighted, and there's no other indication, except for the tiny text "opened this issue".

We keep the tabs highlighted now.

Do we still want the icons? We have one for "patch" in the icon set, but don't have one for "issue" (could maybe repurpose the one for "ledger").
<img width="122" alt="Screenshot 2023-05-16 at 08 32 59" src="https://github.com/radicle-dev/radicle-interface/assets/158411/35607201-fe93-42fd-91b9-e1b683efd684">
<img width="121" alt="Screenshot 2023-05-16 at 08 33 10" src="https://github.com/radicle-dev/radicle-interface/assets/158411/7986ed1e-50f1-41a0-92a0-f14fb74e34d0">

**Comment by cloudhead** [comment]
Yeah I'd say it might still be worth adding an icon somewhere on the actual issue. I like your choices.

Let's try it in the `(open)` badge, though it's a very small badge. At least that's where gh/gl uses will look for it.

**Comment by cloudhead** [comment]
Actually now that I think of it, we probably want these icons on the listing page too, instead of the colored circle, and I wonder if we should pick something simpler for issues, like a `!` or something like the github icon `(·)`. Alternatively a checkmark might also work.
