### ISSUE TITLE
Syntax highlighting in diffs

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#728]
Yes, it's that time of the year :sweat_smile: 

It would really help with code review, even if it's just for Rust and TypeScript at the moment!

**Comment by rudolfs** [comment]
Moved to Radicle

https://app.radicle.xyz/nodes/seed.radicle.xyz/rad:z4V1sjrXqjvFdnCUbxPFqd5p4DtH5/issues/36c60f901d6df7d3ee334bfbfcd6075a68c4bd37
