### ISSUE TITLE
Add visual diff check for markdown footnotes

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#739]
We're not testing markdown footnotes yet, but we should.

Refs: https://github.com/radicle-dev/radicle-interface/pull/737.

**Comment by sebastinez** [comment]
@rudolfs I think the easiest way to solve this is to add some footnotes into one of the markdown documents in the `source-browsing` repo.
But I also don't want to load more things into that repo.

So I'm thinking we should separate markdown rendering/checking into a separate repo fixture, which could even be generated on the fly with the new CLI tooling based on some existing markdown files.

**Comment by rudolfs** [comment]
> So I'm thinking we should separate markdown rendering/checking into a separate repo fixture, which could even be generated on the fly with the new CLI tooling based on some existing markdown files.

Sounds good.
