### ISSUE TITLE
TheGraph query failures

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#74]
We need to handle query failures by retrying. Note that we get `200 OK` sometimes even though there is a failure.

```
Failed to get entities from store: relation "sgd86.project" does not exist, query = "/* qid: 30079ddb410a63f2-fa18b9efba7cf9d9 */\nselect 'Project' as entity, to_jsonb(c.*) as data from (select  * \n  from \"sgd86\".\"project\" c\n where c.\"block_range\" @> $1 and (\"org\" = $2)\n\n order by \"id\"\n limit 100) c -- binds: [13142350, \"0x8152237402e0f194176154c3a6ea1eb99b611482\"]
```

**Comment by sebastinez** [comment]
@cloudhead I tried to get one failure or a false positive but no luck.

As I understand, we always get the `errors` array from `fetch`, in this case, I would propose to call recursively the `querySubgraph` function until there are no errors or we tried 3 times.
In case that 3 tries aren't enough we can throw a custom error eg. `Failure.GraphQueryFailed` and allow the user to retry manually.

Here a excerpt from `utils.ts`:
```diff
diff --git a/src/utils.ts b/src/utils.ts
index b2898ac..9829def 100644
--- a/src/utils.ts
+++ b/src/utils.ts
@@ -155,6 +155,7 @@ export async function querySubgraph(
   url: string,
   query: string,
   variables: Record<string, any>,
+  intent = 0
 ): Promise<null | any> {
   const response = await fetch(url, {
     method: 'POST',
@@ -172,7 +173,8 @@ export async function querySubgraph(
     for (const e of json.errors) {
       console.error("querySubgraph:", e.message);
     }
-    return null;
+    if (intent < 3) querySubgraph(url, query, variables, intent += 1);
+    else return null;
   }
 
   return json.data;
```

**Comment by cloudhead** [comment]
Yeah I like that solution.

The error is very intermitent. Unless they fixed something... but I haven't been getting the error either. Still, I think it's a good idea to do this, since the node that handles the query is randomly selected.

**Comment by sebastinez** [comment]
PR #83 closes this issue
