### ISSUE TITLE
Implement proper pagination

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#740]
So far we added a `More` button in places where there's a lot of data to be queried from the backend. While this works for small amounts of data, it has some drawbacks:
 - for a user it's hard to gauge how much more data there is
 - it's impossible to skip to a specific page
 - while it's possible to create deep-links to a specific page, the UX can be confusing, because pagination will work from that page onwards, but won't show the previous pages
 - it's not possible to deep-link to a specific page
 
Therefore I suggest we implement pagination with the ability to skip to a specific page. Something like this:
  <img width="513" alt="Screenshot 2023-05-08 at 17 22 48" src="https://user-images.githubusercontent.com/158411/236863873-75bdb765-ce19-4989-b830-b31a49955b8d.png">

We want this in the following places:
  - seed project listing https://app.radicle.xyz/seeds/seed.radicle.xyz
  - commit list https://app.radicle.xyz/seeds/seed.radicle.xyz/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5/history/master
  - issue list https://app.radicle.xyz/seeds/seed.radicle.xyz/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5/issues
  - patch list https://app.radicle.xyz/seeds/seed.radicle.xyz/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5/patches

**Comment by cloudhead** [comment]
Hmm I'm not sure -- why would you want to link to a certain page? The pages are arbitrary..

**Comment by cloudhead** [comment]
The only point I agree with is the first: "for a user it's hard to gauge how much more data there is". But we can solve this with eg.
```
[More (85)]
```
So the button would show how many more are lreft to load.

**Comment by cloudhead** [comment]
If we really want more control over this, it would be much more useful to be able to specify a time-range, if we're paginating by timestamp.

**Comment by rudolfs** [comment]
> Hmm I'm not sure -- why would you want to link to a certain page? The pages are arbitrary..

So one use case that comes to mind is that when I'm planning a sprint with a team, we'd open each page in a separate tab and talk through all the issues on that page. And everyone opens the same page on their machine. I do that sometimes also when I go over all the issues by myself.

**Comment by rudolfs** [comment]
> The only point I agree with is the first: "for a user it's hard to gauge how much more data there is". But we can solve this with eg.

But what if I want to jump to the last page and see only the latest issues for example?

**Comment by cloudhead** [comment]
> But what if I want to jump to the last page and see only the latest issues for example?

You can sort the list by ascending time :shrug: 

> So one use case that comes to mind is that when I'm planning a sprint with a team, we'd open each page in a separate tab and talk through all the issues on that page. And everyone opens the same page on their machine. I do that sometimes also when I go over all the issues by myself.

This is a bit niche, but it could also be solved by having a little page marker when you click [More], so you see what issues were loaded (which is good practice anyway).

My general point is that page numbers are arbitrary, so I'd prefer if we pagination was implemented via something meaningful, like timestamps.

**Comment by rudolfs** [comment]
> My general point is that page numbers are arbitrary, so I'd prefer if pagination was implemented via something meaningful, like timestamps.

Do you maybe have an example where this is done the way you imagine is the correct way?

I'm trying to imagine how this feature could look like, because pagination with fixed time ranges would mean that each page would contain a different amount of items. And there would be pages that would be empty, because it's not guaranteed that a certain time range has data.

**Comment by cloudhead** [comment]
The simplest would be to do what github does on the commits page, ie. have an `[Older | Newer]` button. Of course this only makes sense for things that are time-ordered.

You can then combine this with updating the URL so that it contains the time range of the objects being shown, eg. `from=<x>&to=<y>`.

On the backend it's basically just getting the next N items, ordered by time.

**Comment by cloudhead** [comment]
The other advantage of it over page numbers is that it always shows consistent data. If you use page numbers, "Page 4" will change every time an issue is added.

**Comment by rudolfs** [comment]
Closing this for now. Needs more thought.
