### ISSUE TITLE
Improve macOS app icon

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#743]
The macOS icon set could be improved to adhere to Apple standards.

Here's what the app looks now when installed via Chrome.
<img width="1032" alt="Screenshot-2023-05-09-at-10 42 50" src="https://user-images.githubusercontent.com/158411/237054845-75ff1133-e072-4aee-bb86-c020d9a03fda.png">
<img width="241" alt="Screenshot-2023-05-09-at-10 42 56" src="https://user-images.githubusercontent.com/158411/237054860-7092ef11-d8e5-4930-b462-7709fd51ddb3.png">
<img width="432" alt="Screenshot-2023-05-09-at-10 44 38" src="https://user-images.githubusercontent.com/158411/237054862-84892237-2b0b-4518-9cef-eed2e9cd92ea.png">

We might need to hack something together though, because it's not possible to specify macOS icons directly. See https://github.com/photopea/photopea/issues/2644 for hints.

Here are the pixel-perfect assets: [Template - Icon - App-assets.zip](https://github.com/radicle-dev/radicle-interface/files/11429398/Template.-.Icon.-.App-assets.zip)

[Template - Icon - App.psd.zip](https://github.com/radicle-dev/radicle-interface/files/11476472/Template.-.Icon.-.App.psd.zip)

<img width="1840" alt="Screenshot-2023-05-09-at-11 19 47" src="https://user-images.githubusercontent.com/158411/237054968-85253552-dc32-4b24-926e-a55d14575faa.png">

**Comment by cloudhead** [comment]
Can you make the black transparent? :D

**Comment by rudolfs** [comment]
> Can you make the black transparent? :D

Haha, no. Apple doesn't allow that.

**Comment by rudolfs** [comment]
> > Can you make the black transparent? :D
> 
> Haha, no. Apple doesn't allow that.

Hm, I was wrong, Apple doesn't allow it on iOS:

<img width="810" alt="Screenshot 2023-05-11 at 10 26 23" src="https://github.com/radicle-dev/radicle-interface/assets/158411/ad0d9835-4ca8-4ee6-ad91-37e26264109d">

So, I guess we could.

**Comment by cloudhead** [comment]
Yeah indeed. We could try also a circle like spotify and see what we like better.

**Comment by brandonhaslegs** [comment]
Made some options

![image](https://github.com/radicle-dev/radicle-interface/assets/4406983/66347931-2109-4581-9d02-5c382246b0a5)

![image](https://github.com/radicle-dev/radicle-interface/assets/4406983/f277a542-a94b-48df-8685-dc0eb95161f4)

![image](https://github.com/radicle-dev/radicle-interface/assets/4406983/8238850e-45bb-435f-8f7e-ce3d8828c902)

**Comment by rudolfs** [comment]
Love the icons! I think we'll be moving away from the app being installable as a chrome app and make it startable from the CLI, so there won't be a need for an icon. At least initially. We'll use these icons if we figure out a way to start it via the UI at some point.
