### ISSUE TITLE
Projects anchored in org with owner profile don't show up as anchored

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#75]
Eg. https://app.radicle.network/orgs/0xceaa01bd5a428d2910c82bbefe1bc7a8cc6207d9/projects/rad:git:hnrknktqojdakynn6kkkywjuz7xqgm85ziauo/e678629cd37c770c640a2cd997fc76303c815772

This should show "Anchored".

**Comment by sebastinez** [comment]
This bug seems to have been fixed? Or is there some other org with owner profile where this happends?

**Comment by cloudhead** [comment]
Yeah indeed, it's been fixed recently!
