### ISSUE TITLE
Allow e2e tests to use a pre-computed seed fixture to run.

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#757]
With PR #676 we generate at the start of the tests to be run a new seed fixture wich can take up to 13s.

Since the tests only require a `radicle-httpd` instance running on localhost:8080 we should be able to allow users to use a pre-computed seed and skip the `globalSetup` fn

**Comment by rudolfs** [comment]
We added an env variable for this in the original PR:
```
SKIP_FIXTURE_CREATION=1 npm run test:e2e -- tests/e2e/historyRouter.spec.ts --project chromium
```
