### ISSUE TITLE
IPFS Deployment down?

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#775]
I just wanted to check if we still have the IPFS legacy deployment pinned on IPFS, and I wasn't able to do so.

Tried to navigate to http://bafybeid2fxbb3zpbttnunrzm74v7l3qxtgxathiv5ucykh2ojm4dbyqdwi.ipfs.localhost:8080/#/ on my own IPFS node and wasn't able to.
Did we pin the repo on fleek or somewhere?
IMO while we write about it in the README we should provide it.

**Comment by cloudhead** [comment]
At this point I would deprecate it. Heartwood is available for everyone and there's no reason to host the old deployment.

**Comment by sebastinez** [comment]
Will be removing it from the README
