### ISSUE TITLE
Improve patch revision diff view

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#791]
>> @cloudhead: In the revision diff view, I would want to see the revision ids being diffed, not just the commits. Maybe this could be shown somewhere on the right of the tabs?

> @xphoniex: We can show that in-place of patch description, wdyt?

Follow-up from https://github.com/radicle-dev/radicle-interface/pull/769#issuecomment-1551165637.

**Comment by xphoniex** [comment]
Not sure if we still want this as we now have a separate icon for diff... do we still want that in the timeline @cloudhead ?

**Comment by xphoniex** [comment]
how will you use that info @cloudhead ? will you be using revision id to check patch in cli, etc?

**Comment by xphoniex** [comment]
also, another thing which is remaining, is whether to show revision description in-place of patch description in diff page

options:
- patch description (currently)
- last revision description
- descriptions of last revision and the one before that

**Comment by rudolfs** [comment]
Let's punt on this for now. The patch view will get an UX/UI overhaul soon anyway.

[UI](https://www.figma.com/file/FfIFgrdXKq547NsdeGZIsp/%5BDark%5D-Radicle-Web?type=design&node-id=1045-2428&mode=design&t=6Aw11elVQfMwvTuE-0) / [UX](https://www.figma.com/file/pD8s3ugZJIVDrI2Nv7giOI/Patches?type=design&node-id=0-1&mode=design&t=J53uDmNeZgPdkvnk-0) mockups.
