### ISSUE TITLE
Add error handling to issue editing and commenting

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#793]
We make API requests and only handle the happy path. We should inform the user if a API request fails.

**Comment by sebastinez** [comment]
hmm so we have some options here (as usual 😅)

We could show the error below the text area or the buttons.
<img width="692" alt="Bildschirmfoto 2023-06-02 um 09 55 37" src="https://github.com/radicle-dev/radicle-interface/assets/7912302/0e0c5a3a-53ce-4249-8133-319e1a1e7a37">

Or a bit more drastic show a modal that we weren't able to create the comment /reply or issue
<img width="703" alt="Bildschirmfoto 2023-06-02 um 10 02 52" src="https://github.com/radicle-dev/radicle-interface/assets/7912302/7edf2060-d0ec-41b6-9a1c-c76bc698cf03">

**Comment by rudolfs** [comment]
I think for now I'd prefer the error modal here.
Although in the long run it would be nice if we had something more lightweight ([thinking of a toast](https://github.com/radicle-dev/radicle-interface/issues/556) 😄 ).
