### ISSUE TITLE
Test `radicle.local` button

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#803]
We should add tests for authentication with the local radicle node. Test the three states:
- radicle-httpd not running
- radicle-httpd running
- radicle-httpd running and authenticated

For this we'll need to improve the `peerManager` to allow us to stop nodes and only selectively start the `palm` node in tests that need it.

**Comment by sebastinez** [comment]
Hmm so it seems that this has been taken care of with #824 right?
Not sure why we would want currently to add the ability to stop and selectively start ones.

We can for now keep the 3 globalFixtures on port 8080 and selectively start others inlined in tests where needed, those get closed when the test is over.

**Comment by rudolfs** [comment]
We're not yet testing that all three states are reflected in the UI. We should also test the 3 visual states:

1) httpd not running
<img width="360" alt="Screenshot 2023-06-19 at 12 59 24" src="https://github.com/radicle-dev/radicle-interface/assets/158411/46047d3e-394c-4bdc-8103-cbe6abaa49ae">
2) httpd running
<img width="397" alt="Screenshot 2023-06-19 at 12 59 44" src="https://github.com/radicle-dev/radicle-interface/assets/158411/7c283ba2-946e-4bb9-8bbf-e5fd3861527d">
3) authenticated
<img width="354" alt="Screenshot 2023-06-19 at 13 00 06" src="https://github.com/radicle-dev/radicle-interface/assets/158411/08d3cd54-a5b9-41de-ba0d-b7d207af5372">

So far we only test the authentication modal.

**Comment by rudolfs** [comment]
We'll re-work the auth experience anyway, we'll tackle it then.
