### ISSUE TITLE
Make issue/patch author NIDs copyable

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#805]
As requested by @slack-coder:

![radicle_issue_id](https://github.com/radicle-dev/radicle-interface/assets/158411/bccdeab1-ca6a-461e-9f89-b3685e15ac92)

**Comment by sebastinez** [comment]
I think this issue is still valid, but we need some design exploration on how we should allow users to copy them without filling everything with clipboard icons.
@rudolfs maybe a task for an UX designer?

**Comment by teramfo** [comment]
To better determine whether to provide copy functionality in teasers or detail views, I'd like to understand the specific use cases for copying a NID. Could you briefly explain the scenarios where you typically copy the NID for use elsewhere? @slack-coder

Later we can come up with a unified approach to copying that avoids cluttering the interface with clipboard icons.
