### ISSUE TITLE
Icon size in project header

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#810]
I think we should reduce icons to 16x16 so that they look nice with text next to them. Here's what it would look like:

<img width="548" alt="image" src="https://github.com/radicle-dev/radicle-interface/assets/40774/a1262a42-660c-41d3-9780-3c8121e9f06e">

I also would add a bit of spacing for the `[icon] N nodes` between the icon and the text. Might be worth creating a component that has icon + text, since we'll probably start adding icons to some of the other stats/buttons.

**Comment by cloudhead** [comment]
We could already add the patch and issue icons that we use in the patch/issue pages, for example :)

**Comment by rudolfs** [comment]
I wonder if the icon set then would have to be redesigned? @brandonhaslegs

**Comment by brandonhaslegs** [comment]
Probably not, I'd just say resize them to 16px. But you'll probably still need both sizes, so don't throw out the 24px ones!
