### ISSUE TITLE
Height of command text

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#817]
I'm sorry to bring this up, I didn't notice the change until now:

<img width="401" alt="image" src="https://github.com/radicle-dev/radicle-interface/assets/40774/2e745825-7bb3-4dcc-b13f-c54f8605f420">

The command text height was changed from how it previously was, and I think this pop-up looks weird now. The commands look like inline code now.

Could we revert the height of these and all other command text?

Here's a mockup, using `height: 2rem; line-height: 2rem`:

<img width="413" alt="image" src="https://github.com/radicle-dev/radicle-interface/assets/40774/8794a2f3-5bdc-4d31-b29f-5c342fb9cbfc">

This makes it match the `[Clone]` button for eg., and creates a visual hierarchy between the command text and the label underneath.

**Comment by rudolfs** [comment]
The only other place where we use a command at the moment is the connect button. Do we want to have all command components to have the same height? I think it would be weird to have one height in the clone button and then a different height elsewhere.

<img width="430" alt="Screenshot 2023-06-06 at 14 42 54" src="https://github.com/radicle-dev/radicle-interface/assets/158411/d7952667-00e0-4c54-b602-8a8315897e61">

**Comment by rudolfs** [comment]
> This makes it match the [Clone] button for eg., and creates a visual hierarchy between the command text and the label underneath.

We could argue that the color already creates a sense of hierarchy. Also the font size of the label is one level smaller.

**Comment by cloudhead** [comment]
> The only other place where we use a command at the moment is the connect button. Do we want to have all command components to have the same height? I think it would be weird to have one height in the clone button and then a different height elsewhere.

Yes, should be the same height everywhere.

> We could argue that the color already creates a sense of hierarchy. Also the font size of the label is one level smaller.

Not good enough imo.
