### ISSUE TITLE
Order of commit listing in patch is wrong

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-interface#830]
<img width="1211" alt="image" src="https://github.com/radicle-dev/radicle-interface/assets/40774/4895fbec-a650-4961-9c77-efd6269f4e44">

Should be the other way around, ie. chronological like the timeline, otherwise the graph lines don't make sense :)

**Comment by sebastinez** [comment]
Yeah I think it makes sense to have it the other way around.
I think to pull this off, I'll look into `radicle-httpd` and see if we can pass it an option to sort commits by timestamp, ascending and descending
This would allow us also to make some progress with #740

**Comment by cloudhead** [comment]
Why not reverse them in the UI? We don't want to sort by timestamp, we want to sort by parent/child relationship.

**Comment by gsaslis** [comment]
> Why not reverse them in the UI? 

+1 on doing this in `radicle-httpd` so that all other clients can benefit from this.
