### ISSUE TITLE
Missing moved file

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-interface#857]
This patch's commit contains a moved file that wasn't picked up by the interface:
https://app.radicle.xyz/seeds/seed.radicle.xyz/rad:z3gqcJUoA1n9HaHKufZs5FCSGazv5/commits/e33661738c9aeb689f691e84fbf15387fe334238

Could we investigate whether this might be an issue with `radicle-interface` or if it's something lower-level like `radicle-surf`?

**Comment by sebastinez** [comment]
Thanks @FintanH for bringing it up, we missed support for copied and moved files.

**Comment by sebastinez** [comment]
We should probably add a test case for showing a moved and a copied file..
