### ISSUE TITLE
coc-svelte broken after the svelte v4 upgrade

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#870]
The neovim coc-svelte plugin stopped working after we upgraded to Svelte v4.
A [dependency update](https://github.com/rudolfs/coc-svelte/commit/12115a7c924f04fa01cf9ecd2107d10e1d39d764) did not fix the issue this time.

<img width="837" alt="Screenshot 2023-06-26 at 15 39 57" src="https://github.com/radicle-dev/radicle-interface/assets/158411/e528fdf0-3e82-4a5f-b3a0-3e0a16f8e2ad">

**Comment by geigerzaehler** [comment]
I think this only requires a proper update of all dependecies https://github.com/rudolfs/coc-svelte/pull/1

**Comment by rudolfs** [comment]
https://github.com/rudolfs/coc-svelte/commit/7053c10463b7bfed8fad72298245e7397f0e8d8b took care of this.
