### ISSUE TITLE
Usage of ethereum-blockies

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#9]
There is a `declare module` global definition for the `ethereum-blockies` package.
https://github.com/radicle-dev/radicle-interface/blob/master/types/types.d.ts
According to the code base we are implementing our own blockies package, but it's not being used.

I think it's a good way to identify fast a chosen account, and would propose to use it besides the account address.

**Comment by cloudhead** [comment]
Indeed, the `declare` should be removed! We *are* using blockies throughout the codebase (our own version taken from ENS), but perhaps it would be nice to include in the header next to the connected address. Is that what you mean?
