### ISSUE TITLE
Add additional source browsing test

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#904]
https://github.com/radicle-dev/radicle-interface/pull/900#discussion_r1254103764

1. Go to the awesome-radicle project.
2. Select the peer “dave” and one of the branches starting with “patches/”
3. Click on macos-launch-agents
4. Expected to see the the file launchers/macos/​README.md for the peer “dave” and the selected branch

**Comment by sebastinez** [comment]
Hmm this doesn't seem to work for me, the peer is persisted and the file `launchers/macos/​README.md` shows up, but the branch is being reverted to `master``
Not sure if this is a regression, or a not yet fixed bug.

**Comment by rudolfs** [comment]
Moved to Radicle

https://app.radicle.xyz/nodes/seed.radicle.xyz/rad:z4V1sjrXqjvFdnCUbxPFqd5p4DtH5/issues/2ede4a521a34bbe87686333a4da27ae6c68bdc9b

**Comment by rudolfs** [comment]
> Hmm this doesn't seem to work for me, the peer is persisted and the file `launchers/macos/​README.md` shows up, but the branch is being reverted to `master` Not sure if this is a regression, or a not yet fixed bug.

Just tested this, seems to work on prod. Just need a test for it.
