### ISSUE TITLE
Playwright tests interacting with local dev server

### ISSUE THREAD

**Issue by rudolfs** [radicle-dev/radicle-interface#950]
There must be something in the tests that interferes with the local dev server. Investigate what it is and fix it.

```
10:07:03 AM [vite] page reload tests/artifacts/.playwright-artifacts-4/traces/resources/8370527b39a0f13c1a3fde915123342bfe41d547.html
```

<img width="921" alt="Screenshot 2023-07-18 at 10 11 34" src="https://github.com/radicle-dev/radicle-interface/assets/158411/71f1f56d-2bfa-444a-9f64-63b4cab9ac53">

**Comment by sebastinez** [comment]
Hey @rudolfs thanks for catching this issue, can you maybe give a little more detail on what happened?
