### ISSUE TITLE
Show in user profile which orgs the user is member of.

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-interface#98]
Show in the user profile the orgs a user is owner as EOA or part of a Gnosis Safe.

## Design:
![Frame 1](https://user-images.githubusercontent.com/7912302/140895242-a814b1e1-033d-4304-bde5-e944fde68ab7.png)

## Implementation:
I propose to add to the subgraph the ability to return its members:
```diff
type Org @entity {
  id: ID!
  owner: Bytes!
+ members: [Bytes!]! 
  creator: Bytes!
  timestamp: BigInt!
}
```

In case of a EOA org the owner is already part of the subgraph and does not require additional development.
In case of a Gnosis Safe which we could check for with something like: https://github.com/radicle-dev/radicle-interface/blob/b73177ad06e2f48eb067c08eff1e76cc1e46b5ae/src/utils.ts#L338-L345
We should be able to obtain the owners using the following method:
https://github.com/gnosis/safe-contracts/blob/186a21a74b327f17fc41217a927dea7064f74604/contracts/base/OwnerManager.sol#L136
And add the result to the subgraph response.

**Comment by cloudhead** [comment]
Hmmm right, the problem is the subgraph doesn't contain the members of the safe. To do that, we would have to query the ethereum state or somehow track the safe creation in the subgraph :thinking:

**Comment by sebastinez** [comment]
> the problem is the subgraph doesn't contain the members of the safe.
Shouldn't it be possible to query the members of the safe by querying `getOwners()(address[])`?
We could even be listening for the owner change events like
```
event AddedOwner(address owner);
event RemovedOwner(address owner);
```
Or am I missing something?

**Comment by cloudhead** [comment]
Yeah, this might be easy actually, from inside the subgraph. One thing though, to not break APIs and to still know about the safe address, I wouldn't change the type of `owner`. Instead I would just add a `members` array which has one element for EOA orgs.

**Comment by sebastinez** [comment]
Okay will work on this and provide a PR :+1:

**Comment by sebastinez** [comment]
This issue is blocked until the PR https://github.com/radicle-dev/radicle-subgraph/pull/4 is merged and the subgraph updated.
