### ISSUE TITLE
Routing error handling

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-interface#986]
We want to implement handling of errors that are thrown while loading a view in the following stages:

- [ ] Catch all errors thrown while loading a route and show a generic error view with error message and stacktrace ([design](https://www.figma.com/file/zKSJOOeO6qg4GwaFSM8poL/error-UX?type=design&node-id=2-266))
- [x] Add error handling “not found” with views that don’t require us to show navigation context. The errors are: seed not found, project, issue, patch, commit not found. ([design](https://www.figma.com/file/zKSJOOeO6qg4GwaFSM8poL/error-UX?type=design&node-id=1-78))
  - [x] adjust backend to distinguish not found (404) errors from actual server errors (500)
- [x] Add error handling for “file not found” in tree browser ([design](https://www.figma.com/file/zKSJOOeO6qg4GwaFSM8poL/error-UX?type=design&node-id=0-1))

**Comment by rudolfs** [comment]
Moved to Radicle

https://app.radicle.xyz/nodes/seed.radicle.xyz/rad:z4V1sjrXqjvFdnCUbxPFqd5p4DtH5/issues/c1562cad02138454ee7a64203ab79561dbc13c40
